BEGIN;

ALTER TYPE "AccountingEntryOrigin" ADD VALUE 'WAIVER_REGULARIZATION_REVERSAL';
CREATE TYPE "AccountingWaiverReversalRequestStatus" AS ENUM ('REQUESTED', 'COMPLETED', 'REJECTED', 'CANCELLED');
CREATE TYPE "AccountingWaiverReversalReasonCode" AS ENUM ('ACCOUNTING_ERROR', 'INCORRECT_CLASSIFICATION', 'DUPLICATE_REGULARIZATION', 'OTHER');
CREATE TYPE "AccountingWaiverReversalEventType" AS ENUM ('REQUESTED', 'COMPLETED', 'REJECTED', 'CANCELLED');

COMMIT;
