BEGIN;

ALTER TYPE "AccountingEntryOrigin" ADD VALUE IF NOT EXISTS 'WAIVER_REGULARIZATION_REPLACEMENT';

CREATE TYPE "AccountingWaiverReplacementRequestStatus" AS ENUM ('REQUESTED', 'COMPLETED', 'REJECTED', 'CANCELLED');
CREATE TYPE "AccountingWaiverReplacementReasonCode" AS ENUM ('CORRECTED_CLASSIFICATION', 'CORRECTED_AMOUNT', 'CORRECTED_DATE', 'OTHER');
CREATE TYPE "AccountingWaiverReplacementEventType" AS ENUM ('REQUESTED', 'COMPLETED', 'REJECTED', 'CANCELLED');

COMMIT;
