ALTER TYPE "PurchasePaymentStatus" ADD VALUE 'PARTIALLY_SETTLED';
ALTER TYPE "PurchasePaymentStatus" ADD VALUE 'SETTLED';
ALTER TYPE "PurchaseDueDateStatus" ADD VALUE 'SETTLED';
ALTER TYPE "AccountingEntryOrigin" ADD VALUE 'SUPPLIER_CREDIT_REFUND';

CREATE TYPE "SupplierCreditRefundStatus" AS ENUM ('REQUESTED', 'APPROVED', 'POSTED', 'CANCELLED');
