BEGIN;

ALTER TYPE "AccountingEntryOrigin" ADD VALUE IF NOT EXISTS 'CUSTOMER_CREDIT_REFUND';
ALTER TYPE "InvoicePaymentStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_SETTLED';
ALTER TYPE "InvoicePaymentStatus" ADD VALUE IF NOT EXISTS 'SETTLED';
ALTER TYPE "InvoiceDueDateStatus" ADD VALUE IF NOT EXISTS 'SETTLED';

CREATE TYPE "CustomerCreditRefundStatus" AS ENUM (
  'REQUESTED',
  'APPROVED',
  'POSTED',
  'CANCELLED'
);

COMMIT;
