ALTER TYPE "AccountingEntryOrigin" ADD VALUE IF NOT EXISTS 'PURCHASE_CORRECTION_REVERSAL';
ALTER TYPE "CatalogStockMovementType" ADD VALUE IF NOT EXISTS 'PURCHASE_INTERNAL_REVERSAL';

CREATE TYPE "PurchaseVatRecordKind" AS ENUM ('DOCUMENT', 'INTERNAL_CORRECTION_REVERSAL');
CREATE TYPE "PurchaseCorrectionMode" AS ENUM ('REPLACE', 'VOID');
CREATE TYPE "PurchaseCorrectionReasonCode" AS ENUM (
  'DATA_ENTRY_ERROR',
  'DUPLICATE_DOCUMENT',
  'WRONG_SUPPLIER',
  'WRONG_DATE',
  'WRONG_AMOUNT',
  'WRONG_TAX',
  'OTHER'
);
