export const pgcPymesPlan = {
  code: "PGC_PYMES",
  version: "2021.1",
  source: "BOE-A-2007-19966"
} as const;

export type PgcPymesAccountDefinition = {
  code: string;
  name: string;
  type: string;
  isPostable?: boolean;
};

// Cuadro de cuentas oficial del PGC PYMES consolidado a 30/01/2021.
export const pgcPymesOfficialAccounts: readonly PgcPymesAccountDefinition[] = [
  { code: "1", name: "Financiacion basica", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "2", name: "Activo no corriente", type: "ACTIVO_NO_CORRIENTE" },
  { code: "3", name: "Existencias", type: "EXISTENCIAS" },
  { code: "4", name: "Acreedores y deudores por operaciones comerciales", type: "ACREEDORES_DEUDORES" },
  { code: "5", name: "Cuentas financieras", type: "CUENTAS_FINANCIERAS" },
  { code: "6", name: "Compras y gastos", type: "GASTO" },
  { code: "7", name: "Ventas e ingresos", type: "INGRESO" },
  { code: "10", name: "CAPITAL", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "100", name: "Capital social", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "101", name: "Fondo social", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "102", name: "Capital", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "103", name: "Socios por desembolsos no exigidos", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1030", name: "Socios por desembolsos no exigidos, capital social", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1034", name: "Socios por desembolsos no exigidos, capital pendiente de inscripci\u00f3n", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "104", name: "Socios por aportaciones no dinerarias pendientes", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1040", name: "Socios por aportaciones no dinerarias pendientes, capital social", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1044", name: "Socios por aportaciones no dinerarias pendientes, capital pendiente de inscripci\u00f3n", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "108", name: "Acciones o participaciones propias en situaciones especiales", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "109", name: "Acciones o participaciones propias para reducci\u00f3n de capital", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "11", name: "RESERVAS", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "110", name: "Prima de emisi\u00f3n o asunci\u00f3n", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "112", name: "Reserva legal", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "113", name: "Reservas voluntarias", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "114", name: "Reservas especiales", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1140", name: "Reservas para acciones o participaciones de la sociedad dominante", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1141", name: "Reservas estatutarias", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1142", name: "Reserva por capital amortizado", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1144", name: "Reservas por acciones propias aceptadas en garant\u00eda", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "118", name: "Aportaciones de socios o propietarios", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "119", name: "Diferencias por ajuste del capital a euros", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "12", name: "RESULTADOS PENDIENTES DE APLICACI\u00d3N", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "120", name: "Remanente", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "121", name: "Resultados negativos de ejercicios anteriores", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "129", name: "Resultado del ejercicio", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "13", name: "SUBVENCIONES, DONACIONES, LEGADOS Y OTROS AJUSTES EN PATRIMONIO NETO", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "130", name: "Subvenciones oficiales de capital", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "131", name: "Donaciones y legados de capital", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "132", name: "Otras subvenciones, donaciones y legados", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "137", name: "Ingresos fiscales a distribuir en varios ejercicios", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1370", name: "Ingresos fiscales por diferencias permanentes a distribuir en varios ejercicios", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1371", name: "Ingresos fiscales por deducciones y bonificaciones a distribuir en varios ejercicios", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "14", name: "PROVISIONES", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "141", name: "Provisi\u00f3n para impuestos", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "142", name: "Provisi\u00f3n para otras responsabilidades", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "143", name: "Provisi\u00f3n por desmantelamiento, retiro o rehabilitaci\u00f3n del inmovilizado", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "145", name: "Provisi\u00f3n para actuaciones medioambientales", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "15", name: "DEUDAS A LARGO PLAZO CON CARACTER\u00cdSTICAS ESPECIALES", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "150", name: "Acciones o participaciones a largo plazo consideradas como pasivos financieros", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "153", name: "Desembolsos no exigidos por acciones o participaciones consideradas como pasivos financieros", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1533", name: "Desembolsos no exigidos, empresas del grupo", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1534", name: "Desembolsos no exigidos, empresas asociadas", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1535", name: "Desembolsos no exigidos, otras partes vinculadas", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1536", name: "Otros desembolsos no exigidos", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "154", name: "Aportaciones no dinerarias pendientes por acciones o participaciones consideradas como pasivos financieros", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1543", name: "Aportaciones no dinerarias pendientes, empresas del grupo", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1544", name: "Aportaciones no dinerarias pendientes, empresas asociadas", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1545", name: "Aportaciones no dinerarias pendientes, otras partes vinculadas", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1546", name: "Otras aportaciones no dinerarias pendientes", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "16", name: "DEUDAS A LARGO PLAZO CON PARTES VINCULADAS", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "160", name: "Deudas a largo plazo con entidades de cr\u00e9dito vinculadas", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1603", name: "Deudas a largo plazo con entidades de cr\u00e9dito, empresas del grupo", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1604", name: "Deudas a largo plazo con entidades de cr\u00e9dito, empresas asociadas", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1605", name: "Deudas a largo plazo con otras entidades de cr\u00e9dito vinculadas", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "161", name: "Proveedores de inmovilizado a largo plazo, partes vinculadas", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1613", name: "Proveedores de inmovilizado a largo plazo, empresas del grupo", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1614", name: "Proveedores de inmovilizado a largo plazo, empresas asociadas", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1615", name: "Proveedores de inmovilizado a largo plazo, otras partes vinculadas", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "162", name: "Acreedores por arrendamiento financiero a largo plazo, partes vinculadas", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1623", name: "Acreedores por arrendamiento financiero a largo plazo, empresas de grupo", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1624", name: "Acreedores por arrendamiento financiero a largo plazo, empresas asociadas", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1625", name: "Acreedores por arrendamiento financiero a largo plazo, otras partes vinculadas", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "163", name: "Otras deudas a largo plazo con partes vinculadas", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1633", name: "Otras deudas a largo plazo, empresas del grupo", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1634", name: "Otras deudas a largo plazo, empresas asociadas", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "1635", name: "Otras deudas a largo plazo, con otras partes vinculadas", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "17", name: "DEUDAS A LARGO PLAZO POR PR\u00c9STAMOS RECIBIDOS, EMPR\u00c9STITOS Y OTROS CONCEPTOS", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "170", name: "Deudas a largo plazo con entidades de cr\u00e9dito", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "171", name: "Deudas a largo plazo", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "172", name: "Deudas a largo plazo transformables en subvenciones, donaciones y legados", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "173", name: "Proveedores de inmovilizado a largo plazo", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "174", name: "Acreedores por arrendamiento financiero a largo plazo", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "175", name: "Efectos a pagar a largo plazo", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "176", name: "Pasivos por derivados financieros a largo plazo", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "177", name: "Obligaciones y bonos", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "179", name: "Deudas representadas en otros valores negociables", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "18", name: "PASIVOS POR FIANZAS, GARANT\u00cdAS Y OTROS CONCEPTOS A LARGO PLAZO", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "180", name: "Fianzas recibidas a largo plazo", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "181", name: "Anticipos recibidos por ventas o prestaciones de servicios a largo plazo", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "185", name: "Dep\u00f3sitos recibidos a largo plazo", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "19", name: "SITUACIONES TRANSITORIAS DE FINANCIACI\u00d3N", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "190", name: "Acciones o participaciones emitidas", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "192", name: "Suscriptores de acciones", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "194", name: "Capital emitido pendiente de inscripci\u00f3n", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "195", name: "Acciones o participaciones emitidas consideradas como pasivos financieros", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "197", name: "Suscriptores de acciones consideradas como pasivos financieros", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "199", name: "Acciones o participaciones emitidas consideradas como pasivos financieros pendientes de inscripci\u00f3n", type: "PATRIMONIO_NETO_PASIVO" },
  { code: "20", name: "INMOVILIZACIONES INTANGIBLES", type: "ACTIVO_NO_CORRIENTE" },
  { code: "200", name: "Investigaci\u00f3n", type: "ACTIVO_NO_CORRIENTE" },
  { code: "201", name: "Desarrollo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "202", name: "Concesiones administrativas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "205", name: "Derechos de traspaso", type: "ACTIVO_NO_CORRIENTE" },
  { code: "206", name: "Aplicaciones inform\u00e1ticas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "209", name: "Anticipos para inmovilizaciones intangibles", type: "ACTIVO_NO_CORRIENTE" },
  { code: "21", name: "INMOVILIZACIONES MATERIALES", type: "ACTIVO_NO_CORRIENTE" },
  { code: "210", name: "Terrenos y bienes naturales", type: "ACTIVO_NO_CORRIENTE" },
  { code: "211", name: "Construcciones", type: "ACTIVO_NO_CORRIENTE" },
  { code: "212", name: "Instalaciones t\u00e9cnicas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "213", name: "Maquinaria", type: "ACTIVO_NO_CORRIENTE" },
  { code: "214", name: "Utillaje", type: "ACTIVO_NO_CORRIENTE" },
  { code: "215", name: "Otras instalaciones", type: "ACTIVO_NO_CORRIENTE" },
  { code: "216", name: "Mobiliario", type: "ACTIVO_NO_CORRIENTE" },
  { code: "217", name: "Equipos para procesos de informaci\u00f3n", type: "ACTIVO_NO_CORRIENTE" },
  { code: "218", name: "Elementos de transporte", type: "ACTIVO_NO_CORRIENTE" },
  { code: "219", name: "Otro inmovilizado material", type: "ACTIVO_NO_CORRIENTE" },
  { code: "22", name: "INVERSIONES INMOBILIARIAS", type: "ACTIVO_NO_CORRIENTE" },
  { code: "220", name: "Inversiones en terrenos y bienes naturales", type: "ACTIVO_NO_CORRIENTE" },
  { code: "221", name: "Inversiones en construcciones", type: "ACTIVO_NO_CORRIENTE" },
  { code: "23", name: "INMOVILIZACIONES MATERIALES EN CURSO", type: "ACTIVO_NO_CORRIENTE" },
  { code: "230", name: "Adaptaci\u00f3n de terrenos y bienes naturales", type: "ACTIVO_NO_CORRIENTE" },
  { code: "231", name: "Construcciones en curso", type: "ACTIVO_NO_CORRIENTE" },
  { code: "232", name: "Propiedad industrial", type: "ACTIVO_NO_CORRIENTE" },
  { code: "233", name: "Propiedad industrial", type: "ACTIVO_NO_CORRIENTE" },
  { code: "237", name: "Propiedad industrial", type: "ACTIVO_NO_CORRIENTE" },
  { code: "239", name: "Propiedad industrial", type: "ACTIVO_NO_CORRIENTE" },
  { code: "24", name: "EN PARTES VINCULADAS", type: "ACTIVO_NO_CORRIENTE" },
  { code: "240", name: "Participaciones a largo plazo en partes vinculadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2403", name: "Participaciones a largo plazo en empresas del grupo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2404", name: "Participaciones a largo plazo en empresas asociadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2405", name: "Participaciones a largo plazo en otras partes vinculadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "241", name: "Valores representativos de deuda a largo plazo de partes vinculadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2413", name: "Valores representativos de deuda a largo plazo de empresas del grupo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2414", name: "Valores representativos de deuda a largo plazo de empresas asociadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2415", name: "Valores representativos de deuda a largo plazo de otras partes vinculadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "242", name: "Cr\u00e9ditos a largo plazo a partes vinculadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2423", name: "Cr\u00e9ditos a largo plazo a empresas del grupo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2424", name: "Cr\u00e9ditos a largo plazo a empresas asociadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2425", name: "Cr\u00e9ditos a largo plazo a otras partes vinculadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "249", name: "Desembolsos pendientes sobre participaciones a largo plazo en partes vinculadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2493", name: "Desembolsos pendientes sobre participaciones a largo plazo en empresas del grupo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2494", name: "Desembolsos pendientes sobre participaciones a largo plazo en empresas asociadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2495", name: "Desembolsos pendientes sobre participaciones a largo plazo en otras partes vinculadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "25", name: "OTRAS INVERSIONES FINANCIERAS A LARGO PLAZO", type: "ACTIVO_NO_CORRIENTE" },
  { code: "250", name: "Inversiones financieras alargo plazo en instrumentos de patrimonio", type: "ACTIVO_NO_CORRIENTE" },
  { code: "251", name: "Valores representativos de deuda a largo plazo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "252", name: "Cr\u00e9ditos a largo plazo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "253", name: "Cr\u00e9ditos a largo plazo por enajenaci\u00f3n de inmovilizado", type: "ACTIVO_NO_CORRIENTE" },
  { code: "254", name: "Cr\u00e9ditos a largo plazo al personal", type: "ACTIVO_NO_CORRIENTE" },
  { code: "255", name: "Activos por derivados financieros a largo plazo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "258", name: "Imposiciones a largo plazo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "259", name: "Desembolsos pendientes sobre participaciones en el patrimonio neto a largo plazo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "26", name: "FIANZAS Y DEP\u00d3SITOS CONSTITUIDOS A LARGO PLAZO", type: "ACTIVO_NO_CORRIENTE" },
  { code: "260", name: "Fianzas constituidas a largo plazo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "265", name: "Dep\u00f3sitos constituidos a largo plazo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "28", name: "AMORTIZACI\u00d3N ACUMULADA DEL INMOVILIZADO", type: "ACTIVO_NO_CORRIENTE" },
  { code: "280", name: "Amortizaci\u00f3n acumulada del inmovilizado intangible", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2800", name: "Amortizaci\u00f3n acumulada de investigaci\u00f3n", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2801", name: "Amortizaci\u00f3n acumulada de desarrollo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2802", name: "Amortizaci\u00f3n acumulada de concesiones administrativas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2803", name: "Amortizaci\u00f3n acumulada de propiedad industrial", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2805", name: "Amortizaci\u00f3n acumulada de derechos de traspaso", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2806", name: "Amortizaci\u00f3n acumulada de aplicaciones inform\u00e1ticas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "281", name: "Amortizaci\u00f3n acumulada del inmovilizado material", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2811", name: "Amortizaci\u00f3n acumulada de construcciones", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2812", name: "Amortizaci\u00f3n acumulada de instalaciones t\u00e9cnicas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2813", name: "Amortizaci\u00f3n acumulada de maquinaria", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2814", name: "Amortizaci\u00f3n acumulada de utillaje", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2815", name: "Amortizaci\u00f3n acumulada de otras instalaciones", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2816", name: "Amortizaci\u00f3n acumulada de mobiliario", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2817", name: "Amortizaci\u00f3n acumulada de equipos para procesos de informaci\u00f3n", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2818", name: "Amortizaci\u00f3n acumulada de elementos de transporte", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2819", name: "Amortizaci\u00f3n acumulada de otro inmovilizado material", type: "ACTIVO_NO_CORRIENTE" },
  { code: "282", name: "Amortizaci\u00f3n acumulada de las inversiones inmobiliarias", type: "ACTIVO_NO_CORRIENTE" },
  { code: "29", name: "DETERIORO DE VALOR DE ACTIVOS NO CORRIENTES", type: "ACTIVO_NO_CORRIENTE" },
  { code: "290", name: "Deterioro de valor del inmovilizado intangible", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2900", name: "Deterioro de valor de investigaci\u00f3n", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2901", name: "Deterioro de valor de desarrollo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2902", name: "Deterioro de valor de concesiones administrativas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2903", name: "Deterioro de valor de propiedad industrial", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2905", name: "Deterioro de valor de derechos de traspaso", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2906", name: "Deterioro de valor de aplicaciones inform\u00e1ticas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "291", name: "Deterioro de valor del inmovilizado material", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2910", name: "Deterioro de valor de terrenos y bienes naturales", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2911", name: "Deterioro de valor de construcciones", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2912", name: "Deterioro de valor de instalaciones t\u00e9cnicas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2913", name: "Deterioro de valor de maquinaria", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2914", name: "Deterioro de valor de utillaje", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2915", name: "Deterioro de valor de otras instalaciones", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2916", name: "Deterioro de valor de mobiliario", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2917", name: "Deterioro de valor de equipos para procesos de informaci\u00f3n", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2918", name: "Deterioro de valor de elementos de transporte", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2919", name: "Deterioro de valor de otro inmovilizado material", type: "ACTIVO_NO_CORRIENTE" },
  { code: "292", name: "Deterioro de valor de las inversiones inmobiliarias", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2920", name: "Deterioro de valor de los terrenos y bienes naturales", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2921", name: "Deterioro de valor de construcciones", type: "ACTIVO_NO_CORRIENTE" },
  { code: "293", name: "Deterioro de valor de participaciones a largo plazo en partes vinculadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2933", name: "Deterioro de valor de participaciones a largo plazo en empresas del grupo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2934", name: "Deterioro de valor de participaciones a largo plazo en empresas asociadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2935", name: "Deterioro de valor de participaciones a largo plazo en otras partes vinculadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "294", name: "Deterioro de valor de valores representativos de deuda a largo plazo de partes vinculadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2943", name: "Deterioro de valor de valores representativos de deuda a largo plazo de empresas del grupo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2944", name: "Deterioro de valor de valores representativos de deuda a largo plazo de empresas asociadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2945", name: "Deterioro de valor de valores representativos de deuda a largo plazo de otras partes vinculadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "295", name: "Deterioro de valor de cr\u00e9ditos a largo plazo a partes vinculadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2953", name: "Deterioro de valor de cr\u00e9ditos a largo plazo a empresas del grupo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2954", name: "Deterioro de valor de cr\u00e9ditos a largo plazo a empresas asociadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "2955", name: "Deterioro de valor de cr\u00e9ditos a largo plazo a otras partes vinculadas", type: "ACTIVO_NO_CORRIENTE" },
  { code: "296", name: "Deterioro de valor de participaciones en el patrimonio neto a largo plazo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "297", name: "Deterioro de valor de valores representativos de deuda a largo plazo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "298", name: "Deterioro de valor de cr\u00e9ditos a largo plazo", type: "ACTIVO_NO_CORRIENTE" },
  { code: "30", name: "COMERCIALES", type: "EXISTENCIAS" },
  { code: "300", name: "Mercader\u00edas A", type: "EXISTENCIAS" },
  { code: "301", name: "Mercader\u00edas B", type: "EXISTENCIAS" },
  { code: "31", name: "MATERIAS PRIMAS", type: "EXISTENCIAS" },
  { code: "310", name: "Materias primas A", type: "EXISTENCIAS" },
  { code: "311", name: "Materias primas B", type: "EXISTENCIAS" },
  { code: "32", name: "OTROS APROVISIONAMIENTOS", type: "EXISTENCIAS" },
  { code: "320", name: "Elementos y conjuntos incorporables", type: "EXISTENCIAS" },
  { code: "321", name: "Combustibles", type: "EXISTENCIAS" },
  { code: "322", name: "Repuestos", type: "EXISTENCIAS" },
  { code: "325", name: "Materiales diversos", type: "EXISTENCIAS" },
  { code: "326", name: "Embalajes", type: "EXISTENCIAS" },
  { code: "327", name: "Envases", type: "EXISTENCIAS" },
  { code: "328", name: "Material de oficina", type: "EXISTENCIAS" },
  { code: "33", name: "PRODUCTOS EN CURSO", type: "EXISTENCIAS" },
  { code: "330", name: "Productos en curso A", type: "EXISTENCIAS" },
  { code: "331", name: "Productos en curso B", type: "EXISTENCIAS" },
  { code: "34", name: "PRODUCTOS SEMITERMINADOS", type: "EXISTENCIAS" },
  { code: "340", name: "Productos semiterminados A", type: "EXISTENCIAS" },
  { code: "341", name: "Productos semiterminados B", type: "EXISTENCIAS" },
  { code: "35", name: "PRODUCTOS TERMINADOS", type: "EXISTENCIAS" },
  { code: "350", name: "Productos terminados A", type: "EXISTENCIAS" },
  { code: "351", name: "Productos terminados B", type: "EXISTENCIAS" },
  { code: "36", name: "SUBPRODUCTOS, RESIDUOS Y MATERIALES RECUPERADOS", type: "EXISTENCIAS" },
  { code: "360", name: "Subproductos A", type: "EXISTENCIAS" },
  { code: "361", name: "Subproductos B", type: "EXISTENCIAS" },
  { code: "365", name: "Residuos A", type: "EXISTENCIAS" },
  { code: "366", name: "Residuos B", type: "EXISTENCIAS" },
  { code: "368", name: "Materiales recuperados A", type: "EXISTENCIAS" },
  { code: "369", name: "Materiales recuperados B", type: "EXISTENCIAS" },
  { code: "39", name: "DETERIORO DE VALOR DE LAS EXISTENCIAS", type: "EXISTENCIAS" },
  { code: "390", name: "Deterioro de valor de las mercader\u00edas", type: "EXISTENCIAS" },
  { code: "391", name: "Deterioro de valor de las materias primas", type: "EXISTENCIAS" },
  { code: "392", name: "Deterioro de valor de otros aprovisionamientos", type: "EXISTENCIAS" },
  { code: "393", name: "Deterioro de valor de los productos en curso", type: "EXISTENCIAS" },
  { code: "394", name: "Deterioro de valor de los productos semiterminados", type: "EXISTENCIAS" },
  { code: "395", name: "Deterioro de valor de los productos terminados", type: "EXISTENCIAS" },
  { code: "396", name: "Deterioro de valor de los subproductos, residuos y materiales recuperados", type: "EXISTENCIAS" },
  { code: "40", name: "PROVEEDORES", type: "ACREEDORES_DEUDORES" },
  { code: "400", name: "Proveedores", type: "ACREEDORES_DEUDORES" },
  { code: "4000", name: "Proveedores (euros)", type: "ACREEDORES_DEUDORES" },
  { code: "4004", name: "Proveedores (moneda extranjera)", type: "ACREEDORES_DEUDORES" },
  { code: "4009", name: "Proveedores, facturas pendientes de recibir o de formalizar", type: "ACREEDORES_DEUDORES" },
  { code: "401", name: "Proveedores, efectos comerciales a pagar", type: "ACREEDORES_DEUDORES" },
  { code: "403", name: "Proveedores, empresas del grupo", type: "ACREEDORES_DEUDORES" },
  { code: "4030", name: "Proveedores, empresas del grupo (euros)", type: "ACREEDORES_DEUDORES" },
  { code: "4031", name: "Efectos comerciales a pagar, empresas del grupo", type: "ACREEDORES_DEUDORES" },
  { code: "4034", name: "Proveedores, empresas del grupo (moneda extranjera)", type: "ACREEDORES_DEUDORES" },
  { code: "4036", name: "Envases y embalajes a devolver a proveedores, empresas del grupo", type: "ACREEDORES_DEUDORES" },
  { code: "4039", name: "Proveedores, empresas del grupo, facturas pendientes de recibir o de formalizar", type: "ACREEDORES_DEUDORES" },
  { code: "404", name: "Proveedores, empresas asociadas", type: "ACREEDORES_DEUDORES" },
  { code: "405", name: "Proveedores, otras partes vinculadas", type: "ACREEDORES_DEUDORES" },
  { code: "406", name: "Envases y embalajes a devolver a proveedores", type: "ACREEDORES_DEUDORES" },
  { code: "407", name: "Anticipos a proveedores", type: "ACREEDORES_DEUDORES" },
  { code: "41", name: "ACREEDORES VARIOS", type: "ACREEDORES_DEUDORES" },
  { code: "410", name: "Acreedores por prestaciones de servicios", type: "ACREEDORES_DEUDORES" },
  { code: "4100", name: "Acreedores por prestaciones de servicios (euros)", type: "ACREEDORES_DEUDORES" },
  { code: "4104", name: "Acreedores por prestaciones de servicios, (moneda extranjera)", type: "ACREEDORES_DEUDORES" },
  { code: "4109", name: "Acreedores por prestaciones de servicios, facturas pendientes de recibir o de formalizar", type: "ACREEDORES_DEUDORES" },
  { code: "411", name: "Acreedores, efectos comerciales a pagar", type: "ACREEDORES_DEUDORES" },
  { code: "419", name: "Acreedores por operaciones en com\u00fan", type: "ACREEDORES_DEUDORES" },
  { code: "43", name: "CLIENTES", type: "ACREEDORES_DEUDORES" },
  { code: "430", name: "Clientes", type: "ACREEDORES_DEUDORES" },
  { code: "4300", name: "Clientes (euros)", type: "ACREEDORES_DEUDORES" },
  { code: "4304", name: "Clientes (moneda extranjera)", type: "ACREEDORES_DEUDORES" },
  { code: "4309", name: "Clientes, facturas pendientes de formalizar", type: "ACREEDORES_DEUDORES" },
  { code: "431", name: "Clientes, efectos comerciales a cobrar", type: "ACREEDORES_DEUDORES" },
  { code: "4310", name: "Efectos comerciales en cartera", type: "ACREEDORES_DEUDORES" },
  { code: "4311", name: "Efectos comerciales descontados", type: "ACREEDORES_DEUDORES" },
  { code: "4312", name: "Efectos comerciales en gesti\u00f3n de cobro", type: "ACREEDORES_DEUDORES" },
  { code: "4315", name: "Efectos comerciales impagados", type: "ACREEDORES_DEUDORES" },
  { code: "432", name: "Clientes, operaciones de \u00abfactoring\u00bb", type: "ACREEDORES_DEUDORES" },
  { code: "433", name: "Clientes, empresas del grupo", type: "ACREEDORES_DEUDORES" },
  { code: "4330", name: "Clientes empresas del grupo (euros)", type: "ACREEDORES_DEUDORES" },
  { code: "4331", name: "Efectos comerciales a cobrar, empresas del grupo", type: "ACREEDORES_DEUDORES" },
  { code: "4332", name: "Clientes empresas del grupo, operaciones de \u00abfactoring\u00bb", type: "ACREEDORES_DEUDORES" },
  { code: "4334", name: "Clientes empresas del grupo (moneda extranjera)", type: "ACREEDORES_DEUDORES" },
  { code: "4336", name: "Clientes empresas del grupo de dudoso cobro ", type: "ACREEDORES_DEUDORES" },
  { code: "4337", name: "Envases y embalajes a devolver a clientes, empresas del grupo", type: "ACREEDORES_DEUDORES" },
  { code: "4339", name: "Clientes empresas del grupo, facturas pendientes de formalizar", type: "ACREEDORES_DEUDORES" },
  { code: "434", name: "Clientes, empresas asociadas", type: "ACREEDORES_DEUDORES" },
  { code: "435", name: "Clientes, otras partes vinculadas", type: "ACREEDORES_DEUDORES" },
  { code: "436", name: "Clientes de dudoso cobro", type: "ACREEDORES_DEUDORES" },
  { code: "437", name: "Envases y embalajes a devolver por clientes", type: "ACREEDORES_DEUDORES" },
  { code: "438", name: "Anticipos de clientes", type: "ACREEDORES_DEUDORES" },
  { code: "44", name: "DEUDORES VARIOS", type: "ACREEDORES_DEUDORES" },
  { code: "440", name: "Deudores", type: "ACREEDORES_DEUDORES" },
  { code: "4400", name: "Deudores (euros)", type: "ACREEDORES_DEUDORES" },
  { code: "4404", name: "Deudores (moneda extranjera)", type: "ACREEDORES_DEUDORES" },
  { code: "4409", name: "Deudores, facturas pendientes de formalizar", type: "ACREEDORES_DEUDORES" },
  { code: "441", name: "Deudores, efectos comerciales a cobrar", type: "ACREEDORES_DEUDORES" },
  { code: "4410", name: "Deudores, efectos comerciales en cartera", type: "ACREEDORES_DEUDORES" },
  { code: "4411", name: "Deudores, efectos comerciales descontados", type: "ACREEDORES_DEUDORES" },
  { code: "4412", name: "Deudores, efectos comerciales en gesti\u00f3n de cobro", type: "ACREEDORES_DEUDORES" },
  { code: "4415", name: "Deudores, efectos comerciales impagados", type: "ACREEDORES_DEUDORES" },
  { code: "446", name: "Deudores de dudoso cobro", type: "ACREEDORES_DEUDORES" },
  { code: "449", name: "Deudores por operaciones en com\u00fan", type: "ACREEDORES_DEUDORES" },
  { code: "46", name: "PERSONAL", type: "ACREEDORES_DEUDORES" },
  { code: "460", name: "Anticipos de remuneraciones", type: "ACREEDORES_DEUDORES" },
  { code: "465", name: "Remuneraciones pendientes de pago", type: "ACREEDORES_DEUDORES" },
  { code: "47", name: "ADMINISTRACIONES P\u00daBLICAS", type: "ACREEDORES_DEUDORES" },
  { code: "470", name: "Hacienda P\u00fablica, deudora por diversos conceptos", type: "ACREEDORES_DEUDORES" },
  { code: "4700", name: "Hacienda P\u00fablica, deudora por IVA", type: "ACREEDORES_DEUDORES" },
  { code: "4708", name: "Hacienda P\u00fablica, deudora por subvenciones concedidas", type: "ACREEDORES_DEUDORES" },
  { code: "4709", name: "Hacienda P\u00fablica, deudora por devoluci\u00f3n de impuestos", type: "ACREEDORES_DEUDORES" },
  { code: "471", name: "Organismos de la Seguridad Social, deudores", type: "ACREEDORES_DEUDORES" },
  { code: "472", name: "Hacienda P\u00fablica, IVA soportado", type: "ACREEDORES_DEUDORES" },
  { code: "473", name: "Hacienda P\u00fablica, retenciones y pagos a cuenta", type: "ACREEDORES_DEUDORES" },
  { code: "474", name: "Activos por impuesto diferido", type: "ACREEDORES_DEUDORES" },
  { code: "4740", name: "Activos por diferencias temporarias deducibles", type: "ACREEDORES_DEUDORES" },
  { code: "4742", name: "Derechos por deducciones y bonificaciones pendientes de aplicar", type: "ACREEDORES_DEUDORES" },
  { code: "4745", name: "Cr\u00e9dito por p\u00e9rdidas a compensar del ejercicio", type: "ACREEDORES_DEUDORES" },
  { code: "475", name: "Hacienda P\u00fablica, acreedora por conceptos fiscales", type: "ACREEDORES_DEUDORES" },
  { code: "4750", name: "Hacienda P\u00fablica, acreedora por IVA", type: "ACREEDORES_DEUDORES" },
  { code: "4751", name: "Hacienda P\u00fablica, acreedora por retenciones practicadas", type: "ACREEDORES_DEUDORES" },
  { code: "4752", name: "Hacienda P\u00fablica, acreedora por impuesto sobre sociedades", type: "ACREEDORES_DEUDORES" },
  { code: "4758", name: "Hacienda P\u00fablica, acreedora por subvenciones a reintegrar", type: "ACREEDORES_DEUDORES" },
  { code: "476", name: "Organismos de la Seguridad Social, acreedores", type: "ACREEDORES_DEUDORES" },
  { code: "477", name: "Hacienda P\u00fablica, IVA repercutido", type: "ACREEDORES_DEUDORES" },
  { code: "479", name: "Pasivos por diferencias temporarias imponibles", type: "ACREEDORES_DEUDORES" },
  { code: "48", name: "AJUSTES POR PERIODIFICACI\u00d3N", type: "ACREEDORES_DEUDORES" },
  { code: "480", name: "Gastos anticipados", type: "ACREEDORES_DEUDORES" },
  { code: "485", name: "Ingresos anticipados", type: "ACREEDORES_DEUDORES" },
  { code: "49", name: "DETERIORO DE VALOR DE CR\u00c9DITOS COMERCIALES Y PROVISIONES A CORTO PLAZO", type: "ACREEDORES_DEUDORES" },
  { code: "490", name: "Deterioro de valor de cr\u00e9ditos por operaciones comerciales", type: "ACREEDORES_DEUDORES" },
  { code: "493", name: "Deterioro de valor de cr\u00e9ditos por operaciones comerciales con partes vinculadas", type: "ACREEDORES_DEUDORES" },
  { code: "4933", name: "Deterioro de valor de cr\u00e9ditos por operaciones comerciales con empresas del grupo", type: "ACREEDORES_DEUDORES" },
  { code: "4934", name: "Deterioro de valor de cr\u00e9ditos por operaciones comerciales con empresas asociadas", type: "ACREEDORES_DEUDORES" },
  { code: "4935", name: "Deterioro de valor de cr\u00e9ditos por operaciones comerciales con otras partes vinculadas", type: "ACREEDORES_DEUDORES" },
  { code: "499", name: "Provisiones por operaciones comerciales", type: "ACREEDORES_DEUDORES" },
  { code: "4994", name: "Provisi\u00f3n por contratos onerosos", type: "ACREEDORES_DEUDORES" },
  { code: "4999", name: "Provisi\u00f3n para otras operaciones comerciales", type: "ACREEDORES_DEUDORES" },
  { code: "50", name: "EMPR\u00c9STITOS, DEUDAS CON CAR\u00c1CTER\u00cdSTICAS ESPECIALES Y OTRAS EMISIONES AN\u00c1LOGAS A CORTO PLAZO", type: "CUENTAS_FINANCIERAS" },
  { code: "500", name: "Obligaciones y bonos a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "502", name: "Acciones o participaciones a corto plazo consideradas como pasivos financieros", type: "CUENTAS_FINANCIERAS" },
  { code: "505", name: "Deudas representadas en otros valores negociables a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "506", name: "Intereses a corto plazo de empr\u00e9stitos y otras emisiones an\u00e1logas", type: "CUENTAS_FINANCIERAS" },
  { code: "507", name: "Dividendos de acciones o participaciones consideradas como pasivos financieros", type: "CUENTAS_FINANCIERAS" },
  { code: "509", name: "Valores negociables amortizados", type: "CUENTAS_FINANCIERAS" },
  { code: "5090", name: "Obligaciones y bonos amortizados", type: "CUENTAS_FINANCIERAS" },
  { code: "5095", name: "Otros valores negociables amortizados", type: "CUENTAS_FINANCIERAS" },
  { code: "51", name: "DEUDAS A CORTO PLAZO CON PARTES VINCULADAS", type: "CUENTAS_FINANCIERAS" },
  { code: "510", name: "Deudas a corto plazo con entidades de cr\u00e9dito vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5103", name: "Deudas a corto plazo con entidades de cr\u00e9dito, empresas del grupo", type: "CUENTAS_FINANCIERAS" },
  { code: "5104", name: "Deudas a corto plazo con entidades de cr\u00e9dito, empresas asociadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5105", name: "Deudas a corto plazo con otras entidades de cr\u00e9dito vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "511", name: "Proveedores de inmovilizado a corto plazo, partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5113", name: "Proveedores de inmovilizado a corto plazo, empresas del grupo", type: "CUENTAS_FINANCIERAS" },
  { code: "5114", name: "Proveedores de inmovilizado a corto plazo, empresas asociadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5115", name: "Proveedores de inmovilizado a corto plazo, otras partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "512", name: "Acreedores por arrendamiento financiero a corto plazo, partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5123", name: "Acreedores por arrendamiento financiero a corto plazo, empresas del grupo", type: "CUENTAS_FINANCIERAS" },
  { code: "5124", name: "Acreedores por arrendamiento financiero a corto plazo, empresas asociadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5125", name: "Acreedores por arrendamiento financiero a corto plazo, otras partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "513", name: "Otras deudas a corto plazo con partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5133", name: "Otras deudas a corto plazo con empresas del grupo", type: "CUENTAS_FINANCIERAS" },
  { code: "5134", name: "Otras deudas a corto plazo con empresas asociadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5135", name: "Otras deudas a corto plazo con otras partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "514", name: "Intereses a corto plazo de deudas con partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5143", name: "Intereses a corto plazo de deudas, empresas del grupo", type: "CUENTAS_FINANCIERAS" },
  { code: "5144", name: "Intereses a corto plazo de deudas, empresas asociadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5145", name: "Intereses a corto plazo de deudas, otras partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "52", name: "DEUDAS ACORTO PLAZO POR PR\u00c9STAMOS RECIBIDOS Y OTROS CONCEPTOS", type: "CUENTAS_FINANCIERAS" },
  { code: "520", name: "Deudas a corto plazo con entidades de cr\u00e9dito", type: "CUENTAS_FINANCIERAS" },
  { code: "5200", name: "Pr\u00e9stamos a corto plazo de entidades de cr\u00e9dito", type: "CUENTAS_FINANCIERAS" },
  { code: "5201", name: "Deudas a corto plazo por cr\u00e9dito dispuesto", type: "CUENTAS_FINANCIERAS" },
  { code: "5208", name: "Deudas por efectos descontados", type: "CUENTAS_FINANCIERAS" },
  { code: "5209", name: "Deudas por operaciones de \u00abfactoring\u00bb", type: "CUENTAS_FINANCIERAS" },
  { code: "521", name: "Deudas a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "522", name: "Deudas a corto plazo transformables en subvenciones, donaciones y legados", type: "CUENTAS_FINANCIERAS" },
  { code: "523", name: "Proveedores de inmovilizado a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "524", name: "Acreedores por arrendamiento financiero a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "525", name: "Efectos a pagar a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "526", name: "Dividendo activo a pagar", type: "CUENTAS_FINANCIERAS" },
  { code: "527", name: "Intereses a corto plazo de deudas con entidades de cr\u00e9dito", type: "CUENTAS_FINANCIERAS" },
  { code: "528", name: "Intereses a corto plazo de deudas", type: "CUENTAS_FINANCIERAS" },
  { code: "529", name: "Provisiones a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "5291", name: "Provisi\u00f3n a corto plazo para impuestos", type: "CUENTAS_FINANCIERAS" },
  { code: "5292", name: "Provisi\u00f3n a corto plazo para otras responsabilidades", type: "CUENTAS_FINANCIERAS" },
  { code: "5293", name: "Provisi\u00f3n a corto plazo por desmantelamiento, retiro o rehabilitaci\u00f3n del inmovilizado", type: "CUENTAS_FINANCIERAS" },
  { code: "5295", name: "Provisi\u00f3n a corto plazo para actuaciones medioambientales", type: "CUENTAS_FINANCIERAS" },
  { code: "53", name: "INVERSIONES FINANCIERAS A CORTO PLAZO EN PARTES VINCULADAS", type: "CUENTAS_FINANCIERAS" },
  { code: "530", name: "Participaciones a corto plazo en partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5303", name: "Participaciones a corto plazo, en empresas del grupo", type: "CUENTAS_FINANCIERAS" },
  { code: "5304", name: "Participaciones a corto plazo, en empresas asociadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5305", name: "Participaciones a corto plazo, en otras partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "531", name: "Valores representativos de deuda a corto plazo de partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5313", name: "Valores representativos de deuda a corto plazo de empresas del grupo", type: "CUENTAS_FINANCIERAS" },
  { code: "5314", name: "Valores representativos de deuda a corto plazo de empresas asociadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5315", name: "Valores representativos de deuda a corto plazo de otras partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "532", name: "Cr\u00e9ditos a corto plazo a partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5323", name: "Cr\u00e9ditos a corto plazo a empresas del grupo", type: "CUENTAS_FINANCIERAS" },
  { code: "5324", name: "Cr\u00e9ditos a corto plazo a empresas asociadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5325", name: "Cr\u00e9ditos a corto plazo a otras partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "533", name: "Intereses a corto plazo de valores representativos de deuda de partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5333", name: "Intereses a corto plazo de valores representativos de deuda en empresas del grupo", type: "CUENTAS_FINANCIERAS" },
  { code: "5334", name: "Intereses a corto plazo de valores representativos de deuda en empresas asociadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5335", name: "Intereses a corto plazo de valores representativos de deuda en otras partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "534", name: "Intereses a corto plazo de cr\u00e9ditos a partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5343", name: "Intereses a corto plazo de cr\u00e9ditos a empresas del grupo", type: "CUENTAS_FINANCIERAS" },
  { code: "5344", name: "Intereses a corto plazo de cr\u00e9ditos a empresas asociadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5345", name: "Intereses a corto plazo de cr\u00e9ditos a otras partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "535", name: "Dividendo a cobrar de inversiones financieras en partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5353", name: "Dividendo a cobrar de empresas del grupo", type: "CUENTAS_FINANCIERAS" },
  { code: "5354", name: "Dividendo a cobrar de empresas asociadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5355", name: "Dividendo a cobrar de otras partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "539", name: "Desembolsos pendientes sobre participaciones a corto plazo en partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5393", name: "Desembolsos pendientes sobre participaciones a corto plazo en empresas del grupo", type: "CUENTAS_FINANCIERAS" },
  { code: "5394", name: "Desembolsos pendientes sobre participaciones a corto plazo en empresas asociadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5395", name: "Desembolsos pendientes sobre participaciones a corto plazo en otras partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "54", name: "OTRAS INVERSIONES FINANCIERAS A CORTO PLAZO", type: "CUENTAS_FINANCIERAS" },
  { code: "540", name: "Inversiones financieras a corto plazo en instrumentos de patrimonio", type: "CUENTAS_FINANCIERAS" },
  { code: "541", name: "Valores representativos de deuda a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "542", name: "Cr\u00e9ditos a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "543", name: "Cr\u00e9ditos a corto plazo por enajenaci\u00f3n de inmovilizado", type: "CUENTAS_FINANCIERAS" },
  { code: "544", name: "Cr\u00e9ditos a corto plazo al personal", type: "CUENTAS_FINANCIERAS" },
  { code: "545", name: "Dividendo a cobrar", type: "CUENTAS_FINANCIERAS" },
  { code: "546", name: "Intereses a corto plazo de valores representativos de deuda", type: "CUENTAS_FINANCIERAS" },
  { code: "547", name: "Intereses a corto plazo de cr\u00e9ditos", type: "CUENTAS_FINANCIERAS" },
  { code: "548", name: "Imposiciones a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "549", name: "Desembolsos pendientes sobre participaciones en el patrimonio neto a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "55", name: "OTRAS CUENTAS NO BANCARIAS", type: "CUENTAS_FINANCIERAS" },
  { code: "550", name: "Titular de la explotaci\u00f3n", type: "CUENTAS_FINANCIERAS" },
  { code: "551", name: "Cuenta corriente con socios y administradores", type: "CUENTAS_FINANCIERAS" },
  { code: "552", name: "Cuenta corriente con otras personas y entidades vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5523", name: "Cuenta corriente con empresas del grupo", type: "CUENTAS_FINANCIERAS" },
  { code: "5524", name: "Cuenta corriente con empresas asociadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5525", name: "Cuenta corriente con otras partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "554", name: "Cuenta corriente con uniones temporales de empresas y comunidades de bienes", type: "CUENTAS_FINANCIERAS" },
  { code: "555", name: "Partidas pendientes de aplicaci\u00f3n", type: "CUENTAS_FINANCIERAS" },
  { code: "556", name: "Desembolsos exigidos sobre participaciones en el patrimonio neto", type: "CUENTAS_FINANCIERAS" },
  { code: "5563", name: "Desembolsos exigidos sobre participaciones, empresas del grupo", type: "CUENTAS_FINANCIERAS" },
  { code: "5564", name: "Desembolsos exigidos sobre participaciones, empresas asociadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5565", name: "Desembolsos exigidos sobre participaciones, otras partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5566", name: "Desembolsos exigidos sobre participaciones de otras empresas", type: "CUENTAS_FINANCIERAS" },
  { code: "557", name: "Dividendo activo a cuenta", type: "CUENTAS_FINANCIERAS" },
  { code: "558", name: "Socios por desembolsos exigidos", type: "CUENTAS_FINANCIERAS" },
  { code: "5580", name: "Socios por desembolsos exigidos sobre acciones o participaciones ordinarias", type: "CUENTAS_FINANCIERAS" },
  { code: "5585", name: "Socios por desembolsos exigidos sobre acciones o participaciones consideradas como pasivos financieros", type: "CUENTAS_FINANCIERAS" },
  { code: "559", name: "Derivados financieros a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "5590", name: "Activos por derivados financieros a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "5595", name: "Pasivos por derivados financieros a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "56", name: "FIANZAS Y DEP\u00d3SITOS RECIBIDOS Y CONSTITUIDOS A CORTO PLAZO Y AJUSTES POR PERIODIFICACI\u00d3N", type: "CUENTAS_FINANCIERAS" },
  { code: "560", name: "Fianzas recibidas a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "561", name: "Dep\u00f3sitos recibidos a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "565", name: "Fianzas constituidas a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "566", name: "Dep\u00f3sitos constituidos a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "567", name: "Intereses pagados por anticipado", type: "CUENTAS_FINANCIERAS" },
  { code: "568", name: "Intereses cobrados por anticipado", type: "CUENTAS_FINANCIERAS" },
  { code: "57", name: "TESORER\u00cdA", type: "CUENTAS_FINANCIERAS" },
  { code: "570", name: "Caja, euros", type: "CUENTAS_FINANCIERAS" },
  { code: "571", name: "Caja, moneda extranjera", type: "CUENTAS_FINANCIERAS" },
  { code: "572", name: "Bancos e instituciones de cr\u00e9dito c/c vista, euros", type: "CUENTAS_FINANCIERAS" },
  { code: "573", name: "Bancos e instituciones de cr\u00e9dito c/c vista, moneda extranjera", type: "CUENTAS_FINANCIERAS" },
  { code: "574", name: "Bancos e instituciones de cr\u00e9dito, cuentas de ahorro, euros", type: "CUENTAS_FINANCIERAS" },
  { code: "575", name: "Bancos e instituciones de cr\u00e9dito, cuentas de ahorro, moneda extranjera", type: "CUENTAS_FINANCIERAS" },
  { code: "576", name: "Inversiones a corto plazo de gran liquidez", type: "CUENTAS_FINANCIERAS" },
  { code: "59", name: "DETERIORO DEL VALOR DE INVERSIONES FINANCIERAS A CORTO PLAZO", type: "CUENTAS_FINANCIERAS" },
  { code: "593", name: "Deterioro de valor de participaciones a corto plazo en partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5933", name: "Deterioro de valor de participaciones a corto plazo en empresas del grupo", type: "CUENTAS_FINANCIERAS" },
  { code: "5934", name: "Deterioro de valor de participaciones a corto plazo en empresas asociadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5935", name: "Deterioro de valor de participaciones a corto plazo en otras partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "594", name: "Deterioro de valor de valores representativos de deuda a corto plazo de partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5943", name: "Deterioro de valor de valores representativos de deuda a corto plazo de empresas del grupo", type: "CUENTAS_FINANCIERAS" },
  { code: "5944", name: "Deterioro de valor de valores representativos de deuda a corto plazo de empresas asociadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5945", name: "Deterioro de valor de valores representativos de deuda a corto plazo de otras partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "595", name: "Deterioro de valor de cr\u00e9ditos a corto plazo a partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5953", name: "Deterioro de valor de cr\u00e9ditos a corto plazo a empresas del grupo", type: "CUENTAS_FINANCIERAS" },
  { code: "5954", name: "Deterioro de valor de cr\u00e9ditos a corto plazo a empresas asociadas", type: "CUENTAS_FINANCIERAS" },
  { code: "5955", name: "Deterioro de valor de cr\u00e9ditos a corto plazo a otras partes vinculadas", type: "CUENTAS_FINANCIERAS" },
  { code: "596", name: "Deterioro de valor de participaciones a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "597", name: "Deterioro de valor de valores representativos de deuda a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "598", name: "Deterioro de valor de cr\u00e9ditos a corto plazo", type: "CUENTAS_FINANCIERAS" },
  { code: "60", name: "COMPRAS", type: "GASTO" },
  { code: "600", name: "Compras de mercader\u00edas", type: "GASTO" },
  { code: "601", name: "Compras de materias primas", type: "GASTO" },
  { code: "602", name: "Compras de otros aprovisionamientos", type: "GASTO" },
  { code: "606", name: "Proveedores, otras partes vinculadas", type: "GASTO" },
  { code: "6060", name: "Descuentos sobre compras por pronto pago de mercader\u00edas", type: "GASTO" },
  { code: "6061", name: "Descuentos sobre compras por pronto pago de materias primas", type: "GASTO" },
  { code: "6062", name: "Descuentos sobre compras por pronto pago de otros aprovisionamientos", type: "GASTO" },
  { code: "607", name: "Trabajos realizados por otras empresas", type: "GASTO" },
  { code: "608", name: "Devoluciones de compras y operaciones similares", type: "GASTO" },
  { code: "6080", name: "Devoluciones de compras de mercader\u00edas", type: "GASTO" },
  { code: "6081", name: "Devoluciones de compras de materias primas", type: "GASTO" },
  { code: "6082", name: "Devoluciones de compras de otros aprovisionamientos", type: "GASTO" },
  { code: "609", name: "\u00abRappels\u00bb por compras", type: "GASTO" },
  { code: "6090", name: "\u00abRappels\u00bb por compras de mercader\u00edas", type: "GASTO" },
  { code: "6091", name: "\u00abRappels\u00bb por compras de materias primas", type: "GASTO" },
  { code: "6092", name: "\u00abRappels\u00bb por compras de otros aprovisionamientos", type: "GASTO" },
  { code: "61", name: "VARIACI\u00d3N DE EXISTENCIAS", type: "GASTO" },
  { code: "610", name: "Variaci\u00f3n de existencias de mercader\u00edas", type: "GASTO" },
  { code: "611", name: "Variaci\u00f3n de existencias de materias primas", type: "GASTO" },
  { code: "612", name: "Variaci\u00f3n de existencias de otros aprovisionamientos", type: "GASTO" },
  { code: "62", name: "SERVICIOS EXTERIORES", type: "GASTO" },
  { code: "620", name: "Gastos en investigaci\u00f3n y desarrollo del ejercicio", type: "GASTO" },
  { code: "621", name: "Arrendamientos y c\u00e1nones", type: "GASTO" },
  { code: "622", name: "Reparaciones y conservaci\u00f3n", type: "GASTO" },
  { code: "623", name: "Servicios de profesionales independientes", type: "GASTO" },
  { code: "624", name: "Transportes", type: "GASTO" },
  { code: "625", name: "Primas de seguros", type: "GASTO" },
  { code: "626", name: "Servicios bancarios y similares", type: "GASTO" },
  { code: "627", name: "Publicidad, propaganda y relaciones p\u00fablicas", type: "GASTO" },
  { code: "628", name: "Suministros", type: "GASTO" },
  { code: "629", name: "Otros servicios", type: "GASTO" },
  { code: "63", name: "TRIBUTOS", type: "GASTO" },
  { code: "630", name: "Impuesto sobre beneficios", type: "GASTO" },
  { code: "6300", name: "Impuesto corriente", type: "GASTO" },
  { code: "6301", name: "Impuesto diferido", type: "GASTO" },
  { code: "631", name: "Otros tributos", type: "GASTO" },
  { code: "633", name: "Ajustes negativos en la imposici\u00f3n sobre beneficios", type: "GASTO" },
  { code: "634", name: "Ajustes negativos en la imposici\u00f3n indirecta", type: "GASTO" },
  { code: "6341", name: "Ajustes negativos en IVA de activo corriente", type: "GASTO" },
  { code: "6342", name: "Ajustes negativos en IVA de inversiones", type: "GASTO" },
  { code: "636", name: "Devoluci\u00f3n de impuestos", type: "GASTO" },
  { code: "638", name: "Ajustes positivos en la imposici\u00f3n sobre beneficios", type: "GASTO" },
  { code: "639", name: "Ajustes positivos en la imposici\u00f3n indirecta", type: "GASTO" },
  { code: "6391", name: "Ajustes positivos en IVA de activo corriente", type: "GASTO" },
  { code: "6392", name: "Ajustes positivos en IVA de inversiones", type: "GASTO" },
  { code: "64", name: "GASTOS DE PERSONAL", type: "GASTO" },
  { code: "640", name: "Sueldos y salarios", type: "GASTO" },
  { code: "641", name: "Indemnizaciones", type: "GASTO" },
  { code: "642", name: "Seguridad Social a cargo de la empresa", type: "GASTO" },
  { code: "649", name: "Otros gastos sociales", type: "GASTO" },
  { code: "65", name: "OTROS GASTOS DE GESTI\u00d3N", type: "GASTO" },
  { code: "650", name: "P\u00e9rdidas de cr\u00e9ditos comerciales incobrables", type: "GASTO" },
  { code: "651", name: "Resultados de operaciones en com\u00fan", type: "GASTO" },
  { code: "6510", name: "Beneficio transferido (gestor)", type: "GASTO" },
  { code: "6511", name: "P\u00e9rdida soportada (part\u00edcipe o asociado no gestor)", type: "GASTO" },
  { code: "659", name: "Otras p\u00e9rdidas en gesti\u00f3n corriente", type: "GASTO" },
  { code: "66", name: "GASTOS FINANCIEROS", type: "GASTO" },
  { code: "660", name: "Gastos financieros por actualizaci\u00f3n de provisiones", type: "GASTO" },
  { code: "661", name: "Intereses de obligaciones y bonos", type: "GASTO" },
  { code: "6610", name: "Intereses de obligaciones y bonos a largo plazo, empresas del grupo", type: "GASTO" },
  { code: "6611", name: "Intereses de obligaciones y bonos a largo plazo, empresas asociadas", type: "GASTO" },
  { code: "6612", name: "Intereses de obligaciones y bonos a largo plazo, otras partes vinculadas", type: "GASTO" },
  { code: "6613", name: "Intereses de obligaciones y bonos a largo plazo, otras empresas", type: "GASTO" },
  { code: "6615", name: "Intereses de obligaciones y bonos a corto plazo, empresas del grupo", type: "GASTO" },
  { code: "6616", name: "Intereses de obligaciones y bonos a corto plazo, empresas asociadas", type: "GASTO" },
  { code: "6617", name: "Intereses de obligaciones y bonos a corto plazo, otras partes vinculadas", type: "GASTO" },
  { code: "6618", name: "Intereses de obligaciones y bonos a corto plazo, otras empresas", type: "GASTO" },
  { code: "662", name: "Intereses de deudas", type: "GASTO" },
  { code: "6620", name: "Intereses de deudas, empresas del grupo", type: "GASTO" },
  { code: "6621", name: "Intereses de deudas, empresas asociadas", type: "GASTO" },
  { code: "6622", name: "Intereses de deudas, otras partes vinculadas", type: "GASTO" },
  { code: "6623", name: "Intereses de deudas con entidades de cr\u00e9dito", type: "GASTO" },
  { code: "6624", name: "Intereses de deudas, otras empresas", type: "GASTO" },
  { code: "663", name: "P\u00e9rdidas por valoraci\u00f3n de activos y pasivos financieros por su valor razonable", type: "GASTO" },
  { code: "664", name: "Gastor por dividendos de acciones o participaciones consideradas como pasivos financieros", type: "GASTO" },
  { code: "6640", name: "Dividendos de pasivos, empresas del grupo", type: "GASTO" },
  { code: "6641", name: "Dividendos de pasivos, empresas asociadas", type: "GASTO" },
  { code: "6642", name: "Dividendos de pasivos, otras partes vinculadas", type: "GASTO" },
  { code: "6643", name: "Dividendos de pasivos, otras empresas", type: "GASTO" },
  { code: "665", name: "Intereses por descuento de efectos y operaciones de \u00abfactoring\u00bb", type: "GASTO" },
  { code: "6650", name: "Intereses por descuento de efectos en entidades de cr\u00e9dito del grupo", type: "GASTO" },
  { code: "6651", name: "Intereses por descuento de efectos en entidades de cr\u00e9dito asociadas", type: "GASTO" },
  { code: "6652", name: "Intereses por descuento de efectos en otras entidades de cr\u00e9dito vinculadas", type: "GASTO" },
  { code: "6653", name: "Intereses por descuento de efectos en otras entidades de cr\u00e9dito", type: "GASTO" },
  { code: "6654", name: "Intereses por operaciones de \u00abfactoring\u00bb con entidades de cr\u00e9dito del grupo", type: "GASTO" },
  { code: "6655", name: "Intereses por operaciones de \u00abfactoring\u00bb con entidades de cr\u00e9dito asociadas", type: "GASTO" },
  { code: "6656", name: "Intereses por operaciones de \u00abfactoring\u00bb con otras entidades de cr\u00e9dito vinculadas", type: "GASTO" },
  { code: "6657", name: "Intereses por operaciones de \u00abfactoring\u00bb con otras entidades de cr\u00e9dito", type: "GASTO" },
  { code: "666", name: "P\u00e9rdidas en participaciones y valores representativos de deuda", type: "GASTO" },
  { code: "6660", name: "P\u00e9rdidas en valores representativos de deuda a largo plazo, empresas del grupo", type: "GASTO" },
  { code: "6661", name: "P\u00e9rdidas en valores representativos de deuda a largo plazo, empresas asociadas", type: "GASTO" },
  { code: "6662", name: "P\u00e9rdidas en valores representativos de deuda a largo plazo, otras partes vinculadas", type: "GASTO" },
  { code: "6663", name: "P\u00e9rdidas en participaciones y valores representativos de deuda a largo plazo, otras empresas", type: "GASTO" },
  { code: "6665", name: "P\u00e9rdidas en participaciones y valores representativos de deuda a corto plazo, empresas del grupo", type: "GASTO" },
  { code: "6666", name: "P\u00e9rdidas en participaciones y valores representativos de deuda a corto plazo, empresas asociadas", type: "GASTO" },
  { code: "6667", name: "P\u00e9rdidas en valores representativos de deuda a corto plazo, otras partes vinculadas", type: "GASTO" },
  { code: "6668", name: "P\u00e9rdidas en valores representativos de deuda a corto plazo, otras empresas", type: "GASTO" },
  { code: "667", name: "P\u00e9rdidas de cr\u00e9ditos no comerciales", type: "GASTO" },
  { code: "6670", name: "P\u00e9rdidas de cr\u00e9ditos a largo plazo, empresas del grupo", type: "GASTO" },
  { code: "6671", name: "P\u00e9rdidas de cr\u00e9ditos a largo plazo, empresas asociadas", type: "GASTO" },
  { code: "6672", name: "P\u00e9rdidas de cr\u00e9ditos a largo plazo, otras partes vinculadas", type: "GASTO" },
  { code: "6673", name: "P\u00e9rdidas de cr\u00e9ditos a largo plazo, otras empresas", type: "GASTO" },
  { code: "6675", name: "P\u00e9rdidas de cr\u00e9ditos a corto plazo, empresas del grupo", type: "GASTO" },
  { code: "6676", name: "P\u00e9rdidas de cr\u00e9ditos a corto plazo, empresas asociadas", type: "GASTO" },
  { code: "6677", name: "P\u00e9rdidas de cr\u00e9ditos a corto plazo, otras partes vinculadas", type: "GASTO" },
  { code: "6678", name: "P\u00e9rdidas de cr\u00e9ditos a corto plazo, otras empresas", type: "GASTO" },
  { code: "668", name: "Diferencias negativas de cambio", type: "GASTO" },
  { code: "669", name: "Otros gastos financieros", type: "GASTO" },
  { code: "67", name: "P\u00c9RDIDAS PROCEDENTES DE ACTIVOS NO CORRIENTES Y GASTOS EXCEPCIONALES", type: "GASTO" },
  { code: "670", name: "P\u00e9rdidas procedentes del inmovilizado intangible", type: "GASTO" },
  { code: "671", name: "P\u00e9rdidas procedentes del inmovilizado material", type: "GASTO" },
  { code: "672", name: "P\u00e9rdidas procedentes de las inversiones inmobiliarias", type: "GASTO" },
  { code: "673", name: "P\u00e9rdidas procedentes de participaciones a largo plazo en partes vinculadas", type: "GASTO" },
  { code: "6733", name: "P\u00e9rdidas procedentes de participaciones a largo plazo, empresas del grupo", type: "GASTO" },
  { code: "6734", name: "P\u00e9rdidas procedentes de participaciones a largo plazo, empresas asociadas", type: "GASTO" },
  { code: "6735", name: "P\u00e9rdidas procedentes de participaciones a largo plazo, otras partes vinculadas", type: "GASTO" },
  { code: "675", name: "P\u00e9rdidas por operaciones con obligaciones propias", type: "GASTO" },
  { code: "678", name: "Gastos excepcionales", type: "GASTO" },
  { code: "68", name: "DOTACIONES PARA AMORTIZACIONES", type: "GASTO" },
  { code: "680", name: "Amortizaci\u00f3n del inmovilizado intangible", type: "GASTO" },
  { code: "681", name: "Amortizaci\u00f3n del inmovilizado material", type: "GASTO" },
  { code: "682", name: "Amortizaci\u00f3n de las inversiones inmobiliarias", type: "GASTO" },
  { code: "69", name: "P\u00c9RDIDAS POR DETERIORO Y OTRAS DOTACIONES", type: "GASTO" },
  { code: "690", name: "P\u00e9rdidas por deterioro del inmovilizado intangible", type: "GASTO" },
  { code: "691", name: "P\u00e9rdidas por deterioro del inmovilizado material", type: "GASTO" },
  { code: "692", name: "P\u00e9rdidas por deterioro de las inversiones inmobiliarias", type: "GASTO" },
  { code: "693", name: "P\u00e9rdidas por deterioro de existencias", type: "GASTO" },
  { code: "6930", name: "P\u00e9rdidas por deterioro de productos terminados y en curso de fabricaci\u00f3n", type: "GASTO" },
  { code: "6931", name: "P\u00e9rdidas por deterioro de mercader\u00edas", type: "GASTO" },
  { code: "6932", name: "P\u00e9rdidas por deterioro de materias primas", type: "GASTO" },
  { code: "6933", name: "P\u00e9rdidas por deterioro de otros aprovisionamientos", type: "GASTO" },
  { code: "694", name: "P\u00e9rdidas por deterioro de cr\u00e9ditos por operaciones comerciales", type: "GASTO" },
  { code: "695", name: "Dotaci\u00f3n a la provisi\u00f3n por operaciones comerciales", type: "GASTO" },
  { code: "6954", name: "Dotaci\u00f3n a la provisi\u00f3n por contratos onerosos", type: "GASTO" },
  { code: "6959", name: "Dotaci\u00f3n a la provisi\u00f3n para otras operaciones comerciales", type: "GASTO" },
  { code: "696", name: "P\u00e9rdidas por deterioro de participaciones y valores representativos de deuda a largo plazo", type: "GASTO" },
  { code: "6960", name: "P\u00e9rdidas por deterioro de participaciones en instrumentos de patrimonio neto a largo plazo, empresas del grupo", type: "GASTO" },
  { code: "6961", name: "P\u00e9rdidas por deterioro de participaciones en instrumentos de patrimonio neto a largo plazo, empresas asociadas", type: "GASTO" },
  { code: "6962", name: "P\u00e9rdidas por deterioro de participaciones en instrumentos de patrimonio neto a largo plazo, otras partes vinculadas", type: "GASTO" },
  { code: "6963", name: "P\u00e9rdidas por deterioro de participaciones en instrumentos de patrimonio neto a largo plazo, otras empresas", type: "GASTO" },
  { code: "6965", name: "P\u00e9rdidas por deterioro en valores representativos de deuda a largo plazo, empresas del grupo", type: "GASTO" },
  { code: "6966", name: "P\u00e9rdidas por deterioro en valores representativos de deuda a largo plazo, empresas asociadas", type: "GASTO" },
  { code: "6967", name: "P\u00e9rdidas por deterioro en valores representativos de deuda a largo plazo, otras partes vinculadas", type: "GASTO" },
  { code: "6968", name: "P\u00e9rdidas por deterioro en valores representativos de deuda a largo plazo, de otras empresas", type: "GASTO" },
  { code: "697", name: "P\u00e9rdidas por deterioro de cr\u00e9ditos a largo plazo", type: "GASTO" },
  { code: "6970", name: "P\u00e9rdidas por deterioro de cr\u00e9ditos a largo plazo, empresas del grupo", type: "GASTO" },
  { code: "6971", name: "P\u00e9rdidas por deterioro de cr\u00e9ditos a largo plazo, empresas asociadas", type: "GASTO" },
  { code: "6972", name: "P\u00e9rdidas por deterioro de cr\u00e9ditos a largo plazo, otras partes vinculadas", type: "GASTO" },
  { code: "6973", name: "P\u00e9rdidas por deterioro de cr\u00e9ditos a largo plazo, otras empresas", type: "GASTO" },
  { code: "698", name: "P\u00e9rdidas por deterioro de participaciones y valores representativos de deuda a corto plazo", type: "GASTO" },
  { code: "6980", name: "P\u00e9rdidas por deterioro de participaciones en instrumentos de patrimonio neto a corto plazo, empresas del grupo", type: "GASTO" },
  { code: "6981", name: "P\u00e9rdidas por deterioro de participaciones en instrumentos de patrimonio neto a corto plazo, empresas asociadas", type: "GASTO" },
  { code: "6985", name: "P\u00e9rdidas por deterioro en valores representativos de deuda a corto plazo, empresas del grupo", type: "GASTO" },
  { code: "6986", name: "P\u00e9rdidas por deterioro en valores representativos de deuda a corto plazo, empresas asociadas", type: "GASTO" },
  { code: "6987", name: "P\u00e9rdidas por deterioro en valores representativos de deuda a corto plazo, otras partes vinculadas", type: "GASTO" },
  { code: "6988", name: "P\u00e9rdidas por deterioro en valores representativos de deuda a corto plazo, de otras empresas", type: "GASTO" },
  { code: "699", name: "P\u00e9rdidas por deterioro de cr\u00e9ditos a corto plazo", type: "GASTO" },
  { code: "6990", name: "P\u00e9rdidas por deterioro de cr\u00e9ditos a corto plazo, empresas del grupo", type: "GASTO" },
  { code: "6991", name: "P\u00e9rdidas por deterioro de cr\u00e9ditos a corto plazo, empresas asociadas", type: "GASTO" },
  { code: "6992", name: "P\u00e9rdidas por deterioro de cr\u00e9ditos a corto plazo, otras partes vinculadas", type: "GASTO" },
  { code: "6993", name: "P\u00e9rdidas por deterioro de cr\u00e9ditos a corto plazo, otras empresas", type: "GASTO" },
  { code: "70", name: "VENTAS DE MERCADER\u00cdAS, DE PRODUCCI\u00d3N PROPIA, DE SERVICIOS, ETC", type: "INGRESO" },
  { code: "700", name: "Ventas de mercader\u00edas", type: "INGRESO" },
  { code: "701", name: "Ventas de productos terminados", type: "INGRESO" },
  { code: "702", name: "Ventas de productos semiterminados", type: "INGRESO" },
  { code: "703", name: "Ventas de subproductos y residuos", type: "INGRESO" },
  { code: "704", name: "Ventas de envases y embalajes", type: "INGRESO" },
  { code: "705", name: "Prestaciones de servicios", type: "INGRESO" },
  { code: "706", name: "Descuentos sobre ventas por pronto pago", type: "INGRESO" },
  { code: "7060", name: "Descuentos sobre ventas por pronto pago de mercader\u00edas", type: "INGRESO" },
  { code: "7061", name: "Descuentos sobre ventas por pronto pago de productos terminados", type: "INGRESO" },
  { code: "7062", name: "Descuentos sobre ventas por pronto pago de productos semiterminados", type: "INGRESO" },
  { code: "7063", name: "Descuentos sobre ventas por pronto pago de subproductos y residuos", type: "INGRESO" },
  { code: "708", name: "Devoluciones de ventas y operaciones similares", type: "INGRESO" },
  { code: "7080", name: "Devoluciones de ventas de mercader\u00edas", type: "INGRESO" },
  { code: "7081", name: "Devoluciones de ventas de productos terminados", type: "INGRESO" },
  { code: "7082", name: "Devoluciones de ventas de productos semiterminados", type: "INGRESO" },
  { code: "7083", name: "Devoluciones de ventas de subproductos y residuos", type: "INGRESO" },
  { code: "7084", name: "Devoluciones de ventas de envases y embalajes", type: "INGRESO" },
  { code: "709", name: "\u00abRappels\u00bb sobre ventas", type: "INGRESO" },
  { code: "7090", name: "\u00abRappels\u00bb sobre ventas de mercader\u00edas", type: "INGRESO" },
  { code: "7091", name: "\u00abRappels\u00bb sobre ventas de productos terminados", type: "INGRESO" },
  { code: "7092", name: "\u00abRappels\u00bb sobre ventas de productos semiterminados", type: "INGRESO" },
  { code: "7093", name: "\u00abRappels\u00bb sobre ventas de subproductos y residuos", type: "INGRESO" },
  { code: "7094", name: "\u00abRappels\u00bb sobre ventas de envases y embalajes", type: "INGRESO" },
  { code: "71", name: "VARIACI\u00d3N DE EXISTENCIAS", type: "INGRESO" },
  { code: "710", name: "Variaci\u00f3n de existencias de productos en curso", type: "INGRESO" },
  { code: "711", name: "Variaci\u00f3n de existencias de productos semiterminados", type: "INGRESO" },
  { code: "712", name: "Variaci\u00f3n de existencias de productos terminados", type: "INGRESO" },
  { code: "713", name: "Variaci\u00f3n de existencias de subproductos, residuos y materiales recuperados", type: "INGRESO" },
  { code: "73", name: "TRABAJOS REALIZADOS PARA LA EMPRESA", type: "INGRESO" },
  { code: "730", name: "Trabajos realizados para el inmovilizado intangible", type: "INGRESO" },
  { code: "731", name: "Trabajos realizados para el inmovilizado material", type: "INGRESO" },
  { code: "732", name: "Trabajos realizados en inversiones inmobiliarias", type: "INGRESO" },
  { code: "733", name: "Trabajos realizados para el inmovilizado material en curso", type: "INGRESO" },
  { code: "74", name: "SUBVENCIONES, DONACIONES Y LEGADOS", type: "INGRESO" },
  { code: "740", name: "Subvenciones, donaciones y legados a la explotaci\u00f3n", type: "INGRESO" },
  { code: "746", name: "Subvenciones, donaciones y legados de capital transferidos al resultado del ejercicio", type: "INGRESO" },
  { code: "747", name: "Otras subvenciones, donaciones y legados transferidos al resultado del ejercicio", type: "INGRESO" },
  { code: "75", name: "OTROS INGRESOS DE GESTI\u00d3N", type: "INGRESO" },
  { code: "751", name: "Resultados de operaciones en com\u00fan", type: "INGRESO" },
  { code: "7510", name: "P\u00e9rdida transferida (gestor)", type: "INGRESO" },
  { code: "7511", name: "Beneficio atribuido (part\u00edcipe o asociado no gestor)", type: "INGRESO" },
  { code: "752", name: "Ingresos por arrendamientos", type: "INGRESO" },
  { code: "753", name: "Ingresos de propiedad industrial cedida en explotaci\u00f3n", type: "INGRESO" },
  { code: "754", name: "Ingresos por comisiones", type: "INGRESO" },
  { code: "755", name: "Ingresos por servicios al personal", type: "INGRESO" },
  { code: "759", name: "Ingresos por servicios diversos", type: "INGRESO" },
  { code: "76", name: "INGRESOS FINANCIEROS", type: "INGRESO" },
  { code: "760", name: "Ingresos de participaciones en instrumentos de patrimonio", type: "INGRESO" },
  { code: "7600", name: "Ingresos de participaciones en instrumentos de patrimonio, empresas del grupo", type: "INGRESO" },
  { code: "7601", name: "Ingresos de participaciones en instrumentos de patrimonio, empresas asociadas", type: "INGRESO" },
  { code: "7602", name: "Ingresos de participaciones en instrumentos de patrimonio, otras partes vinculadas", type: "INGRESO" },
  { code: "7603", name: "Ingresos de participaciones en instrumentos de patrimonio, otras empresas", type: "INGRESO" },
  { code: "761", name: "Ingresos de valores representativos de deuda", type: "INGRESO" },
  { code: "7610", name: "Ingresos de valores representativos de deuda, empresas del grupo", type: "INGRESO" },
  { code: "7611", name: "Ingresos de valores representativos de deuda, empresas asociadas", type: "INGRESO" },
  { code: "7612", name: "Ingresos de valores representativos de deuda, otras partes vinculadas", type: "INGRESO" },
  { code: "7613", name: "Ingresos de valores representativos de deuda, otras empresas", type: "INGRESO" },
  { code: "762", name: "Ingresos de cr\u00e9ditos", type: "INGRESO" },
  { code: "7620", name: "Ingresos de cr\u00e9ditos a largo plazo", type: "INGRESO" },
  { code: "7621", name: "Ingresos de cr\u00e9ditos a corto plazo", type: "INGRESO" },
  { code: "763", name: "Beneficios por valoraci\u00f3n de activos y pasivos financieros por su valor razonable", type: "INGRESO" },
  { code: "766", name: "Beneficios en participaciones y valores representativos de deuda", type: "INGRESO" },
  { code: "7660", name: "Beneficios en valores representativos de deuda a largo plazo, empresas del grupo", type: "INGRESO" },
  { code: "7661", name: "Beneficios en valores representativos de deuda a largo plazo, empresas asociadas", type: "INGRESO" },
  { code: "7662", name: "Beneficios en valores representativos de deuda a largo plazo, otras partes vinculadas", type: "INGRESO" },
  { code: "7663", name: "Beneficios en participaciones y valores representativos de deuda a largo plazo, otras empresas", type: "INGRESO" },
  { code: "7665", name: "Beneficios en participaciones y valores representativos de deuda a corto plazo, empresas del grupo", type: "INGRESO" },
  { code: "7666", name: "Beneficios en participaciones y valores representativos de deuda a corto plazo, empresas asociadas", type: "INGRESO" },
  { code: "7667", name: "Beneficios en valores representativos de deuda a corto plazo, otras partes vinculadas", type: "INGRESO" },
  { code: "7668", name: "Beneficios en valores representativos de deuda a corto plazo, otras empresas", type: "INGRESO" },
  { code: "768", name: "Diferencias positivas de cambio", type: "INGRESO" },
  { code: "769", name: "Otros ingresos financieros", type: "INGRESO" },
  { code: "77", name: "BENEFICIOS PROCEDENTES DE ACTIVOS NO CORRIENTES E INGRESOS EXCEPCIONALES", type: "INGRESO" },
  { code: "770", name: "Beneficios procedentes del inmovilizado intangible", type: "INGRESO" },
  { code: "771", name: "Beneficios procedentes del inmovilizado material", type: "INGRESO" },
  { code: "772", name: "Beneficios procedentes de las inversiones inmobiliarias", type: "INGRESO" },
  { code: "773", name: "Beneficios procedentes de participaciones a largo plazo en partes vinculadas", type: "INGRESO" },
  { code: "7733", name: "Beneficios procedentes de participaciones a largo plazo, empresas del grupo", type: "INGRESO" },
  { code: "7734", name: "Beneficios procedentes de participaciones a largo plazo, empresas asociadas", type: "INGRESO" },
  { code: "7735", name: "Beneficios procedentes de participaciones a largo plazo, otras partes vinculadas", type: "INGRESO" },
  { code: "775", name: "Beneficios por operaciones con obligaciones propias", type: "INGRESO" },
  { code: "778", name: "Ingresos excepcionales", type: "INGRESO" },
  { code: "79", name: "EXCESOS Y APLICACIONES DE PROVISIONES Y DE P\u00c9RDIDAS POR DETERIORO", type: "INGRESO" },
  { code: "790", name: "Reversi\u00f3n del deterioro del inmovilizado intangible", type: "INGRESO" },
  { code: "791", name: "Reversi\u00f3n del deterioro del inmovilizado material", type: "INGRESO" },
  { code: "792", name: "Reversi\u00f3n del deterioro de las inversiones inmobiliarias", type: "INGRESO" },
  { code: "793", name: "Reversi\u00f3n del deterioro de existencias", type: "INGRESO" },
  { code: "7930", name: "Reversi\u00f3n del deterioro de productos terminados y en curso de fabricaci\u00f3n", type: "INGRESO" },
  { code: "7931", name: "Reversi\u00f3n del deterioro de mercader\u00edas", type: "INGRESO" },
  { code: "7932", name: "Reversi\u00f3n del deterioro de materias primas", type: "INGRESO" },
  { code: "7933", name: "Reversi\u00f3n del deterioro de otros aprovisionamientos", type: "INGRESO" },
  { code: "794", name: "Reversi\u00f3n del deterioro de cr\u00e9ditos por operaciones comerciales", type: "INGRESO" },
  { code: "795", name: "Exceso de provisiones", type: "INGRESO" },
  { code: "7951", name: "Exceso de provisi\u00f3n para impuestos", type: "INGRESO" },
  { code: "7952", name: "Exceso de provisi\u00f3n para otras responsabilidades", type: "INGRESO" },
  { code: "7954", name: "Exceso de provisi\u00f3n por operaciones comerciales", type: "INGRESO" },
  { code: "7955", name: "Exceso de provisi\u00f3n para actuaciones medioambientales", type: "INGRESO" },
  { code: "796", name: "Reversi\u00f3n del deterioro de participaciones y valores representativos de deuda a largo plazo", type: "INGRESO" },
  { code: "7960", name: "Reversi\u00f3n del deterioro de participaciones en instrumentos de patrimonio neto a largo plazo, empresas del grupo", type: "INGRESO" },
  { code: "7961", name: "Reversi\u00f3n del deterioro de participaciones en instrumentos de patrimonio neto a largo plazo, empresas asociadas", type: "INGRESO" },
  { code: "7962", name: "Reversi\u00f3n del deterioro de participaciones en instrumentos de patrimonio neto a largo plazo, otras partes vinculadas", type: "INGRESO" },
  { code: "7963", name: "Reversi\u00f3n del deterioro de participaciones en instrumentos de patrimonio neto a largo plazo, otras empresas", type: "INGRESO" },
  { code: "7965", name: "Reversi\u00f3n del deterioro de valores representativos de deuda a largo plazo, empresas del grupo", type: "INGRESO" },
  { code: "7966", name: "Reversi\u00f3n del deterioro de valores representativos de deuda a largo plazo, empresas asociadas", type: "INGRESO" },
  { code: "7967", name: "Reversi\u00f3n del deterioro de valores representativos de deuda a largo plazo, otras partes vinculadas", type: "INGRESO" },
  { code: "7968", name: "Reversi\u00f3n del deterioro de valores representativos de deuda a largo plazo, otras empresas", type: "INGRESO" },
  { code: "797", name: "Reversi\u00f3n del deterioro de cr\u00e9ditos a largo plazo", type: "INGRESO" },
  { code: "7970", name: "Reversi\u00f3n del deterioro de cr\u00e9ditos a largo plazo, empresas del grupo", type: "INGRESO" },
  { code: "7971", name: "Reversi\u00f3n del deterioro de cr\u00e9ditos a largo plazo, empresas asociadas", type: "INGRESO" },
  { code: "7972", name: "Reversi\u00f3n del deterioro de cr\u00e9ditos a largo plazo, otras partes vinculadas", type: "INGRESO" },
  { code: "7973", name: "Reversi\u00f3n del deterioro de cr\u00e9ditos a largo plazo, otras empresas", type: "INGRESO" },
  { code: "798", name: "Reversi\u00f3n del deterioro de participaciones y valores representativos de deuda a corto plazo", type: "INGRESO" },
  { code: "7980", name: "Reversi\u00f3n del deterioro de participaciones en instrumentos de patrimonio neto a corto plazo, empresas del grupo", type: "INGRESO" },
  { code: "7981", name: "Reversi\u00f3n del deterioro de participaciones en instrumentos de patrimonio neto a corto plazo, empresas asociadas", type: "INGRESO" },
  { code: "7985", name: "Reversi\u00f3n del deterioro en valores representativos de deuda a corto plazo, empresas del grupo", type: "INGRESO" },
  { code: "7986", name: "Reversi\u00f3n del deterioro en valores representativos de deuda a corto plazo, empresas asociadas", type: "INGRESO" },
  { code: "7987", name: "Reversi\u00f3n del deterioro en valores representativos de deuda a corto plazo, otras partes vinculadas", type: "INGRESO" },
  { code: "7988", name: "Reversi\u00f3n del deterioro en valores representativos de deuda a corto plazo, otras empresas", type: "INGRESO" },
  { code: "799", name: "Reversi\u00f3n del deterioro de cr\u00e9ditos a corto plazo", type: "INGRESO" },
  { code: "7990", name: "Reversi\u00f3n del deterioro de cr\u00e9ditos a corto plazo, empresas del grupo", type: "INGRESO" },
  { code: "7991", name: "Reversi\u00f3n del deterioro de cr\u00e9ditos a corto plazo, empresas asociadas", type: "INGRESO" },
  { code: "7992", name: "Reversi\u00f3n del deterioro de cr\u00e9ditos a corto plazo, otras partes vinculadas", type: "INGRESO" },
  { code: "7993", name: "Reversi\u00f3n del deterioro de cr\u00e9ditos a corto plazo, otras empresas", type: "INGRESO" },
  // __OFFICIAL__
] as const;

// Subcuentas operativas de nueve digitos anadidas por CriGestion.
export const pgcPymesOperationalAccounts: readonly PgcPymesAccountDefinition[] = [
  { code: "100000000", name: "Capital social", type: "PATRIMONIO_NETO", isPostable: true },
  { code: "112000000", name: "Reserva legal", type: "PATRIMONIO_NETO", isPostable: true },
  { code: "120000000", name: "Remanente", type: "PATRIMONIO_NETO", isPostable: true },
  { code: "129000000", name: "Resultado del ejercicio", type: "PATRIMONIO_NETO", isPostable: true },
  { code: "216000000", name: "Mobiliario", type: "ACTIVO", isPostable: true },
  { code: "217000000", name: "Equipos para procesos de informacion", type: "ACTIVO", isPostable: true },
  { code: "281600000", name: "Amortizacion acumulada de mobiliario", type: "ACTIVO_CORRECTORA", isPostable: true },
  { code: "281700000", name: "Amortizacion acumulada de equipos informaticos", type: "ACTIVO_CORRECTORA", isPostable: true },
  { code: "300000000", name: "Mercaderias", type: "ACTIVO", isPostable: true },
  { code: "400000000", name: "Proveedores", type: "PASIVO", isPostable: true },
  { code: "410000000", name: "Acreedores por prestaciones de servicios", type: "PASIVO", isPostable: true },
  { code: "430000000", name: "Clientes", type: "ACTIVO", isPostable: true },
  { code: "472000000", name: "Hacienda Publica, IVA soportado", type: "ACTIVO", isPostable: true },
  { code: "475000000", name: "Hacienda Publica, acreedora", type: "PASIVO", isPostable: true },
  { code: "477000000", name: "Hacienda Publica, IVA repercutido", type: "PASIVO", isPostable: true },
  { code: "520000000", name: "Deudas a corto plazo con entidades de credito", type: "PASIVO", isPostable: true },
  { code: "570000000", name: "Caja, euros", type: "ACTIVO", isPostable: true },
  { code: "572000000", name: "Banco principal", type: "ACTIVO", isPostable: true },
  { code: "600000000", name: "Compras de mercaderias", type: "GASTO", isPostable: true },
  { code: "629000000", name: "Otros servicios", type: "GASTO", isPostable: true },
  { code: "700000000", name: "Ventas de mercaderias", type: "INGRESO", isPostable: true },
  { code: "705000000", name: "Prestaciones de servicios", type: "INGRESO", isPostable: true }
] as const;

export const pgcPymesInitialAccounts: readonly PgcPymesAccountDefinition[] = [
  ...pgcPymesOfficialAccounts,
  ...pgcPymesOperationalAccounts
] as const;
