ALTER TYPE "AccountingEntryOrigin" ADD VALUE IF NOT EXISTS 'PURCHASE_INVOICE';
ALTER TYPE "AccountingEntryOrigin" ADD VALUE IF NOT EXISTS 'SUPPLIER_PAYMENT';
ALTER TYPE "CatalogStockMovementType" ADD VALUE IF NOT EXISTS 'PURCHASE_RECEIPT';
