"use client";

import { FormEvent, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { fetchCsrfToken } from "@/modules/platform/presentation/csrf";

type Action = "add-collaborator" | "remove-collaborator" | "reassign";
export function SupportParticipantChangeForm({ incidentId, expectedVersion, responsibleUserId, users, collaborators }: { incidentId: string; expectedVersion: number; responsibleUserId: string; users: Array<{ id: string; displayName: string }>; collaborators: Array<{ id: string; user: { id: string; displayName: string } }> }) {
  const router = useRouter(); const [action, setAction] = useState<Action>("add-collaborator"); const [state, setState] = useState<{ submitting: boolean; message?: string; error?: boolean }>({ submitting: false }); const key = useRef<string | null>(null);
  const activeIds = new Set(collaborators.map((item) => item.user.id)); const addable = users.filter((user) => user.id !== responsibleUserId && !activeIds.has(user.id)); const assignable = users.filter((user) => user.id !== responsibleUserId && !activeIds.has(user.id));
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setState({ submitting: true }); const form = event.currentTarget; const data = new FormData(form); const reason = String(data.get("reason") ?? "").trim();
    const body = action === "add-collaborator" ? { action, expectedVersion, userId: String(data.get("userId")) } : action === "remove-collaborator" ? { action, expectedVersion, collaboratorId: String(data.get("collaboratorId")), reason } : { action, expectedVersion, responsibleUserId: String(data.get("responsibleUserId")), reason };
    key.current ??= crypto.randomUUID();
    try { const response = await fetch(`/api/support/incidents/${incidentId}/participant-changes`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": key.current, "X-CSRF-Token": await fetchCsrfToken() }, body: JSON.stringify(body) }); const result = await response.json().catch(() => null) as { message?: string } | null; if (response.ok) { key.current = null; setState({ submitting: false, message: "Participantes actualizados." }); router.refresh(); return; } if (response.status < 500) key.current = null; setState({ submitting: false, error: true, message: result?.message ?? "No se pudo actualizar la participación." }); }
    catch { setState({ submitting: false, error: true, message: "Resultado incierto. Reintenta sin cambiar los datos." }); }
  }
  return <form className="form-grid" onSubmit={submit}><fieldset disabled={state.submitting}><legend>Participantes</legend><label>Operación<select value={action} onChange={(event) => setAction(event.target.value as Action)}><option value="add-collaborator">Añadir colaborador</option><option value="remove-collaborator" disabled={!collaborators.length}>Retirar colaborador</option><option value="reassign">Reasignar responsable</option></select></label>{action === "add-collaborator" ? <label>Nuevo colaborador<select name="userId" required disabled={!addable.length}>{addable.length ? addable.map((user) => <option key={user.id} value={user.id}>{user.displayName}</option>) : <option value="">No hay técnicos disponibles</option>}</select></label> : null}{action === "remove-collaborator" ? <label>Colaborador<select name="collaboratorId" required>{collaborators.map((item) => <option key={item.id} value={item.id}>{item.user.displayName}</option>)}</select></label> : null}{action === "reassign" ? <label>Nuevo responsable<select name="responsibleUserId" required disabled={!assignable.length}>{assignable.length ? assignable.map((user) => <option key={user.id} value={user.id}>{user.displayName}</option>) : <option value="">No hay técnicos disponibles</option>}</select></label> : null}{action !== "add-collaborator" ? <label>Motivo<textarea name="reason" required minLength={3} maxLength={500} rows={3}/></label> : null}<label className="checkbox-row"><input type="checkbox" required/> Confirmo el cambio y su registro permanente.</label></fieldset><div className="form-actions"><button className="button" disabled={state.submitting || (action === "add-collaborator" ? !addable.length : action === "remove-collaborator" ? !collaborators.length : !assignable.length)}>{state.submitting ? "Guardando…" : "Aplicar cambio"}</button>{state.message ? <p role="status" className={state.error ? "message error" : "message"}>{state.message}</p> : null}</div></form>;
}
