import Link from "next/link";
import { notFound } from "next/navigation";
import { authorizePagePermission } from "@/modules/platform/presentation/pageAccess";
import { getSupportIncident, listSupportIncidentDetailsReferences, listSupportReferences, supportIncidentParamsSchema } from "@/modules/support/application/incidents";
import { SupportActionCreateForm } from "@/modules/support/presentation/SupportActionCreateForm";
import { SupportStatusTransitionForm } from "@/modules/support/presentation/SupportStatusTransitionForm";
import { SupportParticipantChangeForm } from "@/modules/support/presentation/SupportParticipantChangeForm";
import { SupportPriorityChangeForm } from "@/modules/support/presentation/SupportPriorityChangeForm";
import { isSupportIncidentAttachmentCursor, listSupportIncidentAttachmentPage } from "@/modules/support/application/incidentAttachments";
import { SupportIncidentAttachments } from "@/modules/support/presentation/SupportIncidentAttachments";
import { listSupportMergeCandidates } from "@/modules/support/application/merges";
import { SupportIncidentMergeForm } from "@/modules/support/presentation/SupportIncidentMergeForm";
import { SupportIncidentDetailsChangeForm } from "@/modules/support/presentation/SupportIncidentDetailsChangeForm";
import { SupportActionCorrectionForm } from "@/modules/support/presentation/SupportActionCorrectionForm";
import { listSupportIncidentCustomerChangeReferences } from "@/modules/support/application/customerChanges";
import { SupportIncidentCustomerChangeForm } from "@/modules/support/presentation/SupportIncidentCustomerChangeForm";

export const dynamic = "force-dynamic";

export default async function SupportIncidentPage({ params, searchParams }: { params: Promise<{ incidentId: string }>; searchParams: Promise<{ attachmentCursor?: string; customerSearch?: string }> }) {
  const authorization = await authorizePagePermission("Support.View");
  if (!authorization.ok) return <main className="shell"><section className="content"><div className="panel stack"><h1>Incidencia</h1><p className="message error">{authorization.message}</p></div></section></main>;
  const parsed = supportIncidentParamsSchema.safeParse(await params);
  if (!parsed.success) notFound();
  const incident = await getSupportIncident(parsed.data.incidentId, authorization.user);
  if (!incident) notFound();
  const activeCollaborators = incident.collaborators.filter((item) => item.removedAt === null);
  const isMerged = incident.mergedInto !== null;
  const isIncidentMember = authorization.user.id === incident.responsible.id || authorization.user.role.code === "Administrador" || activeCollaborators.some((item) => item.user.id === authorization.user.id);
  const canAddAction = authorization.user.permissions.includes("Support.AddActions") && (authorization.user.id === incident.responsible.id || authorization.user.role.code === "Administrador" || activeCollaborators.some((item) => item.user.id === authorization.user.id)) && incident.status !== "RESOLVED" && incident.status !== "CLOSED";
  const canUploadAttachment = authorization.user.permissions.includes("Support.ManageAttachments") && isIncidentMember && !isMerged;
  const canDownloadAttachment = authorization.user.permissions.includes("Support.DownloadAttachments");
  const canManage = authorization.user.permissions.includes("Support.ManageAssigned") && (authorization.user.id === incident.responsible.id || authorization.user.role.code === "Administrador");
  const isFinalized = incident.status === "RESOLVED" || incident.status === "CLOSED";
  const canReopen = authorization.user.permissions.includes("Support.Reopen") && !isMerged;
  const canMerge = authorization.user.permissions.includes("Support.MergeIncidents") && !isFinalized && !isMerged && (authorization.user.role.code === "Administrador" || authorization.user.id === incident.responsible.id) && incident.mergedIncidents.length === 0;
  const canManageParticipants = authorization.user.permissions.includes("Support.ManageParticipants") && (authorization.user.id === incident.responsible.id || authorization.user.role.code === "Administrador");
  const canChangeCustomer = authorization.user.role.code === "Administrador" && authorization.user.permissions.includes("Support.ChangeIncidentCustomer") && authorization.user.permissions.includes("Customers.View") && !isMerged && incident.mergedIncidents.length === 0;
  const references = canManageParticipants && !isMerged ? await listSupportReferences() : null;
  const detailsReferences = canManage && !isMerged ? await listSupportIncidentDetailsReferences(incident.customer.id) : null;
  const requestedSearchParams = await searchParams;
  const customerSearch = typeof requestedSearchParams.customerSearch === "string" ? requestedSearchParams.customerSearch.trim().slice(0, 120) : "";
  const customerChangeReferences = canChangeCustomer ? await listSupportIncidentCustomerChangeReferences(authorization.user, incident.customer.id, customerSearch) : [];
  const detailCategories = detailsReferences && !detailsReferences.categories.some((category) => category.id === incident.category.id) ? [incident.category, ...detailsReferences.categories] : detailsReferences?.categories ?? [];
  const detailStores = detailsReferences && incident.store && !detailsReferences.stores.some((store) => store.id === incident.store?.id) ? [incident.store, ...detailsReferences.stores] : detailsReferences?.stores ?? [];
  const mergeCandidates = canMerge ? await listSupportMergeCandidates(incident.id, authorization.user) : [];
  const requestedCursor = requestedSearchParams.attachmentCursor ?? null;
  const attachmentCursor = requestedCursor && isSupportIncidentAttachmentCursor(requestedCursor) ? requestedCursor : null;
  const attachmentPage = await listSupportIncidentAttachmentPage(incident.id, authorization.user, attachmentCursor) ?? { attachments: [], nextCursor: null };
  return <main className="shell"><header className="topbar"><div className="brand">CriGestión</div><Link className="button button-secondary" href="/app/support">Volver a incidencias</Link></header><section className="content stack">
    <div className="panel stack"><div><p className="eyebrow">{incident.number}</p><h1>{incident.title}</h1><div className="form-actions"><span aria-label={`Prioridad: ${priorityLabel(incident.priority)}`} className={`badge ${incident.priority === "URGENT" ? "error" : incident.priority === "HIGH" ? "warning" : "neutral"}`}>{priorityLabel(incident.priority)}</span><span className="badge neutral">{statusLabel(incident.status)}</span></div></div><dl className="detail-grid"><div><dt>Cliente</dt><dd>{authorization.user.permissions.includes("Customers.View") ? <Link href={`/app/customers/${incident.customer.id}`}>{incident.customer.code} · {incident.customer.legalName}</Link> : `${incident.customer.code} · ${incident.customer.legalName}`}</dd></div><div><dt>Tienda</dt><dd>{incident.store ? `${incident.store.code} · ${incident.store.name}` : "Sin tienda"}</dd></div><div><dt>Categoría</dt><dd>{incident.category.name}</dd></div><div><dt>Responsable</dt><dd>{incident.responsible.displayName}</dd></div><div><dt>Creada por</dt><dd>{incident.createdBy.displayName}</dd></div><div><dt>Creación</dt><dd><time dateTime={incident.createdAt}>{new Date(incident.createdAt).toLocaleString("es-ES")}</time></dd></div></dl><div><h2>Descripción</h2><p style={{ whiteSpace: "pre-wrap" }}>{incident.description}</p></div>{incident.solution ? <div><h2>Solución vigente</h2><p style={{ whiteSpace: "pre-wrap" }}>{incident.solution}</p></div> : null}{incident.closeReason ? <div><h2>Cierre vigente</h2><p>{closeReasonLabel(incident.closeReason)}{incident.closeReasonDetail ? ` · ${incident.closeReasonDetail}` : ""}</p></div> : null}</div>
    {incident.mergedInto ? <section className="panel stack" aria-labelledby="merged-incident-heading"><div><p className="eyebrow">Registro secundario</p><h2 id="merged-incident-heading">Incidencia fusionada</h2></div><p>Esta incidencia quedó cerrada como duplicada y permanece disponible para conservar su historial.</p><div className="form-actions"><span className="badge neutral">Duplicada</span><Link className="button button-secondary" href={`/app/support/incidents/${incident.mergedInto.id}`}>Ver principal {incident.mergedInto.number}</Link></div></section> : null}
    <div className="panel stack"><h2>Actuaciones</h2>{incident.actions.length === 0 ? <p className="muted">Todavía no hay actuaciones registradas.</p> : incident.actions.map((action) => {
      const isOwnSource = action.sourceIncident?.id === incident.id;
      const canCorrectAction = authorization.user.permissions.includes("Support.CorrectActions") && !isMerged && isOwnSource && (authorization.user.role.code === "Administrador" || (action.author.id === authorization.user.id && isIncidentMember));
      return <article className="compact-stack" key={action.id}><div><strong>{action.author.displayName}</strong> · <time dateTime={action.performedAt}>{new Date(action.performedAt).toLocaleString("es-ES")}</time>{action.sourceIncident && !isOwnSource ? ` · Origen: ${action.sourceIncident.number}` : ""}{action.version > 1 ? ` · Versión ${action.version}` : ""}</div><p style={{ whiteSpace: "pre-wrap" }}>{action.text}</p>{action.performedAt !== action.recordedAt ? <span className="cell-detail">Registrada: {new Date(action.recordedAt).toLocaleString("es-ES")}</span> : null}{action.corrections.length ? <details><summary>Ver correcciones ({action.corrections.length}{action.correctionsHasMore ? "+" : ""})</summary><div className="stack">{action.correctionsHasMore && action.sourceIncident ? <p><Link href={`/app/support/incidents/${action.sourceIncident.id}/actions/${action.id}/corrections`}>Consultar el historial completo</Link></p> : null}{action.corrections.map((correction) => <article className="compact-stack" key={correction.id}><div><strong>Corrección v{correction.version}</strong> · {correction.correctedBy.displayName} · <time dateTime={correction.correctedAt}>{new Date(correction.correctedAt).toLocaleString("es-ES")}</time></div><p style={{ whiteSpace: "pre-wrap" }}><strong>Anterior:</strong> {correction.previousText}</p><p style={{ whiteSpace: "pre-wrap" }}><strong>Corregido:</strong> {correction.correctedText}</p><p><strong>Motivo:</strong> {correction.reason}</p></article>)}</div></details> : null}{canCorrectAction ? <details><summary>Corregir actuación</summary><SupportActionCorrectionForm incidentId={incident.id} incidentVersion={incident.version} action={{ id: action.id, text: action.text, version: action.version }}/></details> : null}</article>;
    })}</div>
    {authorization.user.permissions.includes("Support.ViewCommunications") ? <div className="panel stack"><h2>Comunicaciones vinculadas</h2>{incident.communications.length === 0 ? <p className="muted">Todavía no hay comunicaciones vinculadas.</p> : incident.communications.map((communication) => <article className="compact-stack" key={communication.id}><div><strong>{communication.channel === "PHONE" ? "Teléfono" : "WhatsApp"}</strong> · {communication.direction === "INBOUND" ? "Entrante" : "Saliente"} · <time dateTime={communication.occurredAt}>{new Date(communication.occurredAt).toLocaleString("es-ES")}</time>{communication.sourceIncident.id !== incident.id ? ` · Origen: ${communication.sourceIncident.number}` : ""}{communication.sourceCustomer.id !== incident.customer.id ? ` · Cliente histórico: ${communication.sourceCustomer.code} · ${communication.sourceCustomer.legalName}` : ""}</div><p style={{ whiteSpace: "pre-wrap" }}>{communication.summary}</p><Link href={`/app/support/communications/${communication.id}`}>Ver comunicación</Link></article>)}</div> : null}
    <SupportIncidentAttachments incidentId={incident.id} attachments={attachmentPage.attachments} nextCursor={attachmentPage.nextCursor} canUpload={canUploadAttachment} canDownload={canDownloadAttachment}/>
    {canAddAction ? <div className="panel stack"><SupportActionCreateForm incidentId={incident.id} expectedVersion={incident.version} createdAt={incident.createdAt}/></div> : null}
    {canManage && !isMerged && detailsReferences ? <div className="panel stack"><SupportIncidentDetailsChangeForm incident={{ id: incident.id, version: incident.version, title: incident.title, description: incident.description, categoryId: incident.category.id, storeId: incident.store?.id ?? null }} categories={detailCategories} stores={detailStores}/></div> : null}
    {canChangeCustomer ? <div className="panel stack"><form className="form-grid" method="get"><label>Buscar cliente por código o nombre<input name="customerSearch" defaultValue={customerSearch} maxLength={120}/></label><div className="form-actions"><button className="button button-secondary" type="submit">Buscar cliente</button>{customerSearch ? <Link className="button button-ghost" href={`/app/support/incidents/${incident.id}`}>Limpiar búsqueda</Link> : null}</div></form><SupportIncidentCustomerChangeForm incident={{ id: incident.id, version: incident.version, customerId: incident.customer.id, hasStore: incident.store !== null }} customers={customerChangeReferences}/></div> : null}
    {canManage && !isFinalized ? <div className="panel stack"><SupportPriorityChangeForm incidentId={incident.id} expectedVersion={incident.version} currentPriority={incident.priority}/></div> : null}
    {!isMerged && (canManage || canReopen) ? <div className="panel stack"><SupportStatusTransitionForm incidentId={incident.id} expectedVersion={incident.version} status={incident.status} canManage={canManage} canReopen={canReopen}/></div> : null}
    {canMerge ? <div className="panel stack"><SupportIncidentMergeForm duplicateIncident={{ id: incident.id, number: incident.number, version: incident.version }} candidates={mergeCandidates}/></div> : null}
    <div className="panel stack"><h2>Equipo de la incidencia</h2><p><strong>Responsable:</strong> {incident.responsible.displayName}</p>{activeCollaborators.length ? <ul>{activeCollaborators.map((item) => <li key={item.id}>{item.user.displayName}</li>)}</ul> : <p className="muted">Sin colaboradores activos.</p>}</div>
    {!isMerged && canManageParticipants && references ? <div className="panel stack"><SupportParticipantChangeForm incidentId={incident.id} expectedVersion={incident.version} responsibleUserId={incident.responsible.id} users={references.responsibleUsers} collaborators={activeCollaborators}/></div> : null}
    {incident.mergedIncidents.length ? <section className="panel stack" aria-labelledby="merged-incidents-heading"><h2 id="merged-incidents-heading">Incidencias duplicadas fusionadas ({incident.mergedIncidents.length})</h2><ul>{incident.mergedIncidents.map((merged) => <li key={merged.id}><Link href={`/app/support/incidents/${merged.id}`}><strong>{merged.number}</strong> · {merged.title}</Link></li>)}</ul></section> : null}
    {incident.participantChanges.length ? <div className="panel stack"><h2>Historial de participación</h2>{incident.participantChanges.map((change) => <article className="compact-stack" key={change.id}><div><strong>{participantChangeLabel(change.type)}</strong> · {change.actor.displayName} · <time dateTime={change.occurredAt}>{new Date(change.occurredAt).toLocaleString("es-ES")}</time></div><p>{change.type === "RESPONSIBLE_CHANGED" ? `${change.fromResponsible?.displayName ?? "—"} → ${change.toResponsible?.displayName ?? "—"}` : change.collaborator?.user.displayName}</p>{change.reason ? <p><strong>Motivo:</strong> {change.reason}</p> : null}</article>)}</div> : null}
    {incident.transitions.length ? <div className="panel stack"><h2>Transiciones de estado</h2>{incident.transitions.map((transition) => <article className="compact-stack" key={transition.id}><div><strong>{statusLabel(transition.fromStatus)} → {statusLabel(transition.toStatus)}</strong> · {transition.actor.displayName} · <time dateTime={transition.occurredAt}>{new Date(transition.occurredAt).toLocaleString("es-ES")}</time></div>{transition.reason ? <p><strong>Motivo:</strong> {transition.reason}</p> : null}{transition.solution ? <p style={{ whiteSpace: "pre-wrap" }}><strong>Solución:</strong> {transition.solution}</p> : null}{transition.closeReason ? <p><strong>Cierre:</strong> {closeReasonLabel(transition.closeReason)}{transition.closeReasonDetail ? ` · ${transition.closeReasonDetail}` : ""}</p> : null}</article>)}</div> : null}
    {incident.priorityChanges.length ? <div className="panel stack"><h2>Cambios de prioridad</h2>{incident.priorityChanges.map((change) => <article className="compact-stack" key={change.id}><div><strong>{priorityLabel(change.fromPriority)} → {priorityLabel(change.toPriority)}</strong> · {change.actor.displayName} · <time dateTime={change.occurredAt}>{new Date(change.occurredAt).toLocaleString("es-ES")}</time></div><p><strong>Motivo:</strong> {change.reason}</p></article>)}</div> : null}
    {incident.detailsChanges.length ? <div className="panel stack"><h2>Cambios de datos principales</h2>{incident.detailsChangesHasMore ? <p>Se muestran los 100 cambios más recientes. La evidencia anterior permanece conservada en PostgreSQL.</p> : null}{incident.detailsChanges.map((change) => <article className="compact-stack" key={change.id}><div><strong>Datos actualizados</strong> · {change.actor.displayName} · <time dateTime={change.changedAt}>{new Date(change.changedAt).toLocaleString("es-ES")}</time></div>{change.previousTitle !== change.correctedTitle ? <p><strong>Título:</strong> {change.previousTitle} → {change.correctedTitle}</p> : null}{change.previousCategory.id !== change.correctedCategory.id ? <p><strong>Categoría:</strong> {change.previousCategory.name} → {change.correctedCategory.name}</p> : null}{change.previousStore?.id !== change.correctedStore?.id ? <p><strong>Tienda:</strong> {change.previousStore ? `${change.previousStore.code} · ${change.previousStore.name}` : "Sin tienda"} → {change.correctedStore ? `${change.correctedStore.code} · ${change.correctedStore.name}` : "Sin tienda"}</p> : null}{change.previousDescription !== change.correctedDescription ? <details><summary>Ver cambio de descripción</summary><div className="stack"><p style={{ whiteSpace: "pre-wrap" }}><strong>Anterior:</strong> {change.previousDescription}</p><p style={{ whiteSpace: "pre-wrap" }}><strong>Nueva:</strong> {change.correctedDescription}</p></div></details> : null}<p><strong>Motivo:</strong> {change.reason}</p></article>)}</div> : null}
    {incident.customerChanges.length ? <div className="panel stack"><h2>Cambios administrativos de cliente</h2>{incident.customerChangesHasMore ? <p>Se muestran los 100 cambios más recientes. La evidencia anterior permanece conservada en PostgreSQL.</p> : null}{incident.customerChanges.map((change) => <article className="compact-stack" key={change.id}><div><strong>Cliente corregido</strong> · {change.actor.displayName} · <time dateTime={change.changedAt}>{new Date(change.changedAt).toLocaleString("es-ES")}</time></div><p><strong>Cliente:</strong> {change.previousCustomer.code} · {change.previousCustomer.legalName} → {change.correctedCustomer.code} · {change.correctedCustomer.legalName}</p><p><strong>Motivo:</strong> {change.reason}</p></article>)}</div> : null}
    <div className="panel stack"><h2>Historial</h2><div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Evento</th><th>Usuario</th><th>Estado</th></tr></thead><tbody>{incident.events.map((event) => <tr key={event.id}><td><time dateTime={event.createdAt}>{new Date(event.createdAt).toLocaleString("es-ES")}</time></td><td>{event.type === "CREATED" ? "Incidencia creada" : event.type === "ACTION_ADDED" ? "Actuación registrada" : event.type === "ACTION_CORRECTED" ? "Actuación corregida" : event.type === "CUSTOMER_CHANGED" ? "Cliente corregido" : event.type === "STATUS_CHANGED" ? "Estado actualizado" : event.type === "PRIORITY_CHANGED" ? "Prioridad actualizada" : event.type === "DETAILS_CHANGED" ? "Datos principales actualizados" : event.type === "INCIDENT_MERGED" ? "Fusión de incidencias" : participantChangeLabel(event.type)}</td><td>{event.actor.displayName}</td><td>{event.toStatus ? statusLabel(event.toStatus) : "—"}</td></tr>)}</tbody></table></div></div>
  </section></main>;
}

function priorityLabel(value: string) { return ({ LOW: "Baja", MEDIUM: "Media", HIGH: "Alta", URGENT: "Urgente" } as Record<string, string>)[value] ?? value; }
function statusLabel(value: string) { return ({ NEW: "Nueva", IN_PROGRESS: "En curso", PENDING_CUSTOMER: "Pendiente del cliente", PENDING_THIRD_PARTY: "Pendiente de tercero", RESOLVED: "Resuelta", CLOSED: "Cerrada" } as Record<string, string>)[value] ?? value; }
function closeReasonLabel(value: string) { return ({ DUPLICATE: "Duplicada", NOT_APPLICABLE: "No procede", CUSTOMER_WITHDRAWS: "Desistimiento del cliente", UNREACHABLE: "Cliente ilocalizable", RESOLVED_EXTERNALLY: "Resuelta externamente", OTHER: "Otros" } as Record<string, string>)[value] ?? value; }
function participantChangeLabel(value: string) { return ({ COLLABORATOR_ADDED: "Colaborador añadido", COLLABORATOR_REMOVED: "Colaborador retirado", RESPONSIBLE_CHANGED: "Responsable reasignado" } as Record<string, string>)[value] ?? value; }
