"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { fetchCsrfToken } from "@/modules/platform/presentation/csrf";
import type { BankAccountDto, BankMovementDto, ReconciliationCandidateDto, ReconciliationProposalDto } from "@/modules/treasury/application/banking";

type State = { kind: "idle" | "submitting" | "success" | "error"; message?: string };

async function postJson(url: string, body: unknown): Promise<{ ok: boolean; message: string }> {
  const csrf = await fetchCsrfToken();
  const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID(), "X-CSRF-Token": csrf }, body: JSON.stringify(body) });
  const result = await response.json().catch(() => null) as { message?: string; code?: string } | null;
  return { ok: response.ok, message: response.ok ? "Operacion completada." : result?.message ?? result?.code ?? "No se pudo completar la operacion." };
}

export function BankAccountCreateForm() {
  const router = useRouter(); const [state, setState] = useState<State>({ kind: "idle" });
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setState({ kind: "submitting" }); const data = new FormData(event.currentTarget); const result = await postJson("/api/treasury/bank-accounts", { name: String(data.get("name") ?? ""), iban: String(data.get("iban") ?? ""), currency: "EUR" }); setState({ kind: result.ok ? "success" : "error", message: result.message }); if (result.ok) { event.currentTarget.reset(); router.refresh(); } }
  return <form className="form-grid" onSubmit={submit}><fieldset disabled={state.kind === "submitting"}><legend>Nueva cuenta bancaria</legend><div className="form-two-columns"><label>Nombre<input name="name" required maxLength={120} /></label><label>IBAN<input name="iban" required maxLength={34} autoComplete="off" /></label></div></fieldset><ActionState state={state} label="Crear cuenta" /></form>;
}

export function BankMovementCreateForm({ accounts }: { accounts: BankAccountDto[] }) {
  const router = useRouter(); const [state, setState] = useState<State>({ kind: "idle" });
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setState({ kind: "submitting" }); const data = new FormData(event.currentTarget); const result = await postJson("/api/treasury/bank-movements", { bankAccountId: String(data.get("bankAccountId") ?? ""), bookingDate: String(data.get("bookingDate") ?? ""), amount: String(data.get("amount") ?? ""), reference: String(data.get("reference") ?? "") || undefined, counterpartyName: String(data.get("counterpartyName") ?? "") || undefined, externalMovementNumber: String(data.get("externalMovementNumber") ?? "") || undefined, currency: "EUR" }); setState({ kind: result.ok ? "success" : "error", message: result.message }); if (result.ok) { event.currentTarget.reset(); router.refresh(); } }
  return <form className="form-grid" onSubmit={submit}><fieldset disabled={state.kind === "submitting" || accounts.length === 0}><legend>Nuevo movimiento</legend><div className="form-three-columns"><label>Cuenta<select name="bankAccountId" required>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name} · {account.maskedIban}</option>)}</select></label><label>Fecha<input name="bookingDate" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} /></label><label>Importe EUR<input name="amount" inputMode="decimal" required pattern="-?\d+\.\d{2}" placeholder="121.00" /></label><label>Referencia<input name="reference" maxLength={140} /></label><label>Contraparte<input name="counterpartyName" maxLength={200} /></label><label>Numero externo<input name="externalMovementNumber" maxLength={120} /></label></div></fieldset><ActionState state={state} label="Crear movimiento" disabled={accounts.length === 0} /></form>;
}

export function Norma43ImportForm({ accounts }: { accounts: BankAccountDto[] }) {
  const router = useRouter(); const [state, setState] = useState<State>({ kind: "idle" });
  const [preview, setPreview] = useState<{ bankAccountId: string; contentBase64: string; dateFrom: string; dateTo: string; openingBalance: string; closingBalance: string; movementCount: number; duplicate: boolean; overlap: boolean } | null>(null);
  async function previewFile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setState({ kind: "submitting" }); const data = new FormData(event.currentTarget); const file = data.get("file"); if (!(file instanceof File)) { setState({ kind: "error", message: "Seleccione un fichero." }); return; } const contentBase64 = bytesToBase64(new Uint8Array(await file.arrayBuffer())); const bankAccountId = String(data.get("bankAccountId") ?? ""); const result = await postJsonWithBody("/api/treasury/bank-statements/preview", { bankAccountId, contentBase64 }); if (!result.ok) { setState({ kind: "error", message: result.message }); return; } const value = result.body as Omit<NonNullable<typeof preview>, "bankAccountId" | "contentBase64">; setPreview({ ...value, bankAccountId, contentBase64 }); setState({ kind: "success", message: "Vista previa validada." }); }
  async function confirmImport() { if (!preview) return; setState({ kind: "submitting" }); const result = await postJsonWithBody("/api/treasury/bank-statements", { bankAccountId: preview.bankAccountId, contentBase64: preview.contentBase64 }); setState({ kind: result.ok ? "success" : "error", message: result.ok ? "Extracto importado." : result.message }); if (result.ok) { setPreview(null); router.refresh(); } }
  return <form className="form-grid" onSubmit={previewFile}><fieldset disabled={state.kind === "submitting" || accounts.length === 0}><legend>Importar Norma 43</legend><div className="form-two-columns"><label>Cuenta<select name="bankAccountId" required>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name} · {account.maskedIban}</option>)}</select></label><label>Fichero AEB43<input name="file" type="file" accept=".txt,.n43" required /></label></div><p className="muted">Perfil AEB43 junio 2012, ASCII, 80 bytes y una cuenta por fichero. Maximo 5 MiB.</p></fieldset><div className="form-actions"><button className="button button-secondary" type="submit" disabled={state.kind === "submitting" || accounts.length === 0}>Validar vista previa</button>{preview ? <><span className="message" role="status">{preview.dateFrom} a {preview.dateTo} · {preview.movementCount} movimientos · saldo {preview.openingBalance} → {preview.closingBalance} EUR</span><button className="button" type="button" onClick={confirmImport} disabled={preview.duplicate || preview.overlap || state.kind === "submitting"}>Confirmar importacion</button>{preview.duplicate ? <span className="message error">El fichero ya fue importado.</span> : null}{preview.overlap ? <span className="message error">El periodo se solapa con otro extracto.</span> : null}</> : null}{state.message ? <span role={state.kind === "error" ? "alert" : "status"} className={state.kind === "error" ? "message error" : "message"}>{state.message}</span> : null}</div></form>;
}

export function BankReconciliationForm({ movement, candidates }: { movement: BankMovementDto; candidates: Array<ReconciliationCandidateDto | ReconciliationProposalDto> }) {
  const router = useRouter(); const [state, setState] = useState<State>({ kind: "idle" });
  const [selectedPaymentId, setSelectedPaymentId] = useState("");
  const selectedCandidate = candidates.find((candidate) => candidate.paymentId === selectedPaymentId);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setState({ kind: "submitting" }); const data = new FormData(event.currentTarget); const result = await postJson("/api/treasury/bank-reconciliations", { bankMovementId: movement.id, applications: [{ customerPaymentId: String(data.get("customerPaymentId") ?? ""), amount: String(data.get("amount") ?? "") }] }); setState({ kind: result.ok ? "success" : "error", message: result.message }); if (result.ok) router.refresh(); }
  return <form className="form-grid" onSubmit={submit}><fieldset disabled={state.kind === "submitting"}><legend>Conciliar movimiento</legend><p className="muted">Pendiente: {movement.pendingAmount} EUR. Las propuestas son orientativas y siempre requieren confirmacion manual.</p><div className="form-two-columns"><label>Propuesta o cobro manual<select name="customerPaymentId" required value={selectedPaymentId} onChange={(event) => setSelectedPaymentId(event.currentTarget.value)}><option value="">Seleccione un cobro</option>{candidates.map((candidate) => <option key={candidate.paymentId} value={candidate.paymentId}>{"score" in candidate ? `${candidate.score} puntos · ` : "Manual · "}{candidate.invoiceNumber ?? "Sin numero"} · {candidate.customerName} · disponible {candidate.availableAmount} EUR</option>)}</select></label><label>Importe<input key={selectedPaymentId} name="amount" required inputMode="decimal" pattern="\d+\.\d{2}" disabled={!selectedCandidate} defaultValue={selectedCandidate && "suggestedAmount" in selectedCandidate ? selectedCandidate.suggestedAmount : selectedCandidate ? minMoney(movement.pendingAmount, selectedCandidate.availableAmount) : ""} /></label></div>{selectedCandidate && "reasons" in selectedCandidate ? <p className="message" role="status">Confianza {confidenceLabel(selectedCandidate.confidence)}: {selectedCandidate.reasons.join(" · ")}</p> : selectedCandidate ? <p className="muted" role="status">Seleccion manual sin puntuacion automatica.</p> : null}{candidates.length === 0 ? <p className="muted" role="status">No hay cobros disponibles para conciliar.</p> : null}</fieldset><ActionState state={state} label="Confirmar conciliacion" disabled={!selectedCandidate || movement.pendingAmount === "0.00"} /></form>;
}

export function UndoBankReconciliationButton({ reconciliationId }: { reconciliationId: string }) {
  const router = useRouter(); const [state, setState] = useState<State>({ kind: "idle" });
  async function undo() { if (!window.confirm("¿Deshacer esta conciliacion?")) return; setState({ kind: "submitting" }); const result = await postJson(`/api/treasury/bank-reconciliations/${reconciliationId}/undo`, {}); setState({ kind: result.ok ? "success" : "error", message: result.message }); if (result.ok) router.refresh(); }
  return <span className="button-row"><button className="button button-secondary button-small" type="button" disabled={state.kind === "submitting"} onClick={undo}>Deshacer</button>{state.message ? <small className={state.kind === "error" ? "message error" : "message"}>{state.message}</small> : null}</span>;
}

function ActionState({ state, label, disabled = false }: { state: State; label: string; disabled?: boolean }) { return <div className="form-actions"><button className="button" type="submit" disabled={disabled || state.kind === "submitting"}>{state.kind === "submitting" ? "Guardando..." : label}</button>{state.message ? <p role={state.kind === "error" ? "alert" : "status"} aria-live="polite" className={state.kind === "error" ? "message error" : "message"}>{state.message}</p> : null}</div>; }
function minMoney(a: string, b: string): string { return Math.min(Number(a), Number(b)).toFixed(2); }
function confidenceLabel(value: "HIGH" | "MEDIUM" | "LOW"): string { return value === "HIGH" ? "alta" : value === "MEDIUM" ? "media" : "baja"; }
async function postJsonWithBody(url: string, body: unknown): Promise<{ ok: boolean; message: string; body: unknown }> { const csrf = await fetchCsrfToken(); const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID(), "X-CSRF-Token": csrf }, body: JSON.stringify(body) }); const value = await response.json().catch(() => null) as { message?: string; code?: string } | null; return { ok: response.ok, message: value?.message ?? value?.code ?? (response.ok ? "Operacion completada." : "No se pudo completar la operacion."), body: value }; }
function bytesToBase64(bytes: Uint8Array): string { let binary = ""; for (let offset = 0; offset < bytes.length; offset += 8192) binary += String.fromCharCode(...bytes.subarray(offset, offset + 8192)); return btoa(binary); }
