"use client";

import { FormEvent, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { BankAccountDto } from "@/modules/treasury/application/banking";
import type { SupplierCreditDetail } from "@/modules/treasury/application/supplierCredits";
import { fetchCsrfToken } from "@/modules/platform/presentation/csrf";

type State = { status: "idle" | "submitting" } | { status: "success" | "error"; message: string };
type Action = "approve" | "post" | "cancel";

export function SupplierCreditApplicationForm({ credit }: { credit: SupplierCreditDetail }) {
  const router = useRouter(); const key = useRef<string | null>(null); const [state, setState] = useState<State>({ status: "idle" });
  const [dueId, setDueId] = useState(credit.eligibleDueDates[0]?.id ?? ""); const due = credit.eligibleDueDates.find((row) => row.id === dueId);
  const maximum = Math.min(Number(credit.availableAmount), Number(due?.pendingAmount ?? 0)).toFixed(2); const disabled = state.status === "submitting" || !due;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setState({ status: "submitting" }); try { key.current ??= crypto.randomUUID(); const response = await fetch(`/api/treasury/supplier-credits/${credit.id}/applications`, { method: "POST", headers: await headers(key.current), body: JSON.stringify({ targetDueDateId: String(data.get("targetDueDateId") ?? ""), applicationDate: String(data.get("applicationDate") ?? ""), amount: String(data.get("amount") ?? ""), notes: optional(data.get("notes")) }) }); const body = await responseBody(response); if (!response.ok) { if (response.status < 500) key.current = null; return setState({ status: "error", message: body?.message ?? body?.code ?? "No se pudo compensar el saldo." }); } key.current = null; setState({ status: "success", message: "Saldo compensado sin movimiento de tesoreria." }); router.refresh(); } catch { setState({ status: "error", message: "Resultado incierto. Reintenta sin recargar para reutilizar la clave idempotente." }); } }
  return <form className="form-grid" onSubmit={submit} aria-busy={state.status === "submitting"}><fieldset disabled={disabled}><legend>Compensar con una compra pendiente</legend><p className="muted">Reduce el crédito y el vencimiento; no crea un pago ni un asiento adicional.</p><div className="form-three-columns"><label>Compra y vencimiento<select name="targetDueDateId" required value={dueId} onChange={(event) => setDueId(event.currentTarget.value)}>{credit.eligibleDueDates.map((row) => <option key={row.id} value={row.id}>{row.supplierInvoiceNumber} · {formatDate(row.dueDate)} · {formatMoney(row.pendingAmount)}</option>)}</select></label><label>Fecha<input name="applicationDate" type="date" required min={credit.sourcePurchase.issueDate} defaultValue={today()} /></label><label>Importe<input key={`${dueId}-${maximum}`} name="amount" required inputMode="decimal" pattern="[0-9]+([.][0-9]{2})" defaultValue={maximum} /><small>Máximo {formatMoney(maximum)}.</small></label></div><label>Observaciones internas<input name="notes" maxLength={500} /></label><label className="checkbox-label"><input type="checkbox" required />Confirmo que la compra pertenece al mismo proveedor y que no existe entrada de dinero.</label></fieldset><div className="form-actions"><button className="button" disabled={disabled}>{state.status === "submitting" ? "Compensando..." : "Compensar saldo"}</button>{!due ? <p className="muted">No hay vencimientos elegibles.</p> : null}<Message state={state} /></div></form>;
}

export function SupplierCreditRefundRequestForm({ credit, bankAccounts }: { credit: SupplierCreditDetail; bankAccounts: BankAccountDto[] }) {
  const router = useRouter(); const key = useRef<string | null>(null); const [state, setState] = useState<State>({ status: "idle" }); const [method, setMethod] = useState<"BANK_TRANSFER" | "CASH">("BANK_TRANSFER");
  const accounts = bankAccounts.filter((account) => account.status === "ACTIVE" && account.currency === credit.currency); const disabled = state.status === "submitting" || Number(credit.availableAmount) <= 0 || (method === "BANK_TRANSFER" && accounts.length === 0);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setState({ status: "submitting" }); try { key.current ??= crypto.randomUUID(); const response = await fetch(`/api/treasury/supplier-credits/${credit.id}/refund-requests`, { method: "POST", headers: await headers(key.current), body: JSON.stringify({ paymentMethod: method, bankAccountId: method === "BANK_TRANSFER" ? String(data.get("bankAccountId") ?? "") : null, requestedDate: String(data.get("requestedDate") ?? ""), amount: String(data.get("amount") ?? ""), reasonCode: String(data.get("reasonCode") ?? ""), reference: optional(data.get("reference")), notes: optional(data.get("notes")) }) }); const body = await responseBody(response); if (!response.ok) { if (response.status < 500) key.current = null; return setState({ status: "error", message: body?.message ?? body?.code ?? "No se pudo solicitar el reembolso." }); } key.current = null; setState({ status: "success", message: "Reembolso solicitado; el importe queda reservado." }); router.refresh(); } catch { setState({ status: "error", message: "Resultado incierto. Reintenta sin recargar para reutilizar la clave idempotente." }); } }
  return <form className="form-grid" onSubmit={submit} aria-busy={state.status === "submitting"}><fieldset disabled={disabled}><legend>Solicitar reembolso del proveedor</legend><p className="message warning">Requiere aprobación por otra persona antes de contabilizar la entrada en banco o caja.</p><div className="form-three-columns"><label>Método<select value={method} name="paymentMethod" onChange={(event) => setMethod(event.currentTarget.value as typeof method)}><option value="BANK_TRANSFER">Transferencia bancaria</option><option value="CASH">Caja</option></select></label>{method === "BANK_TRANSFER" ? <label>Cuenta de entrada<select name="bankAccountId" required defaultValue={accounts[0]?.id ?? ""}>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name} · {account.maskedIban}</option>)}</select></label> : <div><span className="data-label">Cuenta contable</span><strong>570 Caja</strong></div>}<label>Fecha solicitada<input name="requestedDate" type="date" required min={credit.sourcePurchase.issueDate} defaultValue={today()} /></label></div><div className="form-three-columns"><label>Importe<input name="amount" required inputMode="decimal" pattern="[0-9]+([.][0-9]{2})" defaultValue={credit.availableAmount} /></label><label>Motivo<select name="reasonCode" required defaultValue=""><option value="" disabled>Selecciona</option><option value="SUPPLIER_REQUEST">Solicitud del proveedor</option><option value="DUPLICATE_OR_EXCESS">Duplicidad o exceso</option><option value="OPERATION_CANCELLED">Operación cancelada</option><option value="OTHER">Otro</option></select></label><label>Referencia<input name="reference" maxLength={120} /></label></div><label>Observaciones internas<input name="notes" maxLength={500} /></label><label className="checkbox-label"><input type="checkbox" required />Confirmo importe, método y necesidad de aprobación independiente.</label></fieldset><div className="form-actions"><button className="button" disabled={disabled}>{state.status === "submitting" ? "Solicitando..." : "Solicitar reembolso"}</button>{method === "BANK_TRANSFER" && accounts.length === 0 ? <p className="message warning">No hay cuenta bancaria activa en EUR.</p> : null}<Message state={state} /></div></form>;
}

export function SupplierCreditRefundAction({ refundId, action }: { refundId: string; action: Action }) {
  const router = useRouter(); const key = useRef<string | null>(null); const [state, setState] = useState<State>({ status: "idle" }); const copy = actionCopy(action); const [postingDate, setPostingDate] = useState(today());
  async function run() { if (!window.confirm(copy.confirmation)) return; setState({ status: "submitting" }); try { key.current ??= crypto.randomUUID(); const response = await fetch(`/api/treasury/supplier-credit-refunds/${refundId}/${action}`, { method: "POST", headers: await headers(key.current), body: JSON.stringify(action === "post" ? { postingDate } : {}) }); const body = await responseBody(response); if (!response.ok) { if (response.status < 500) key.current = null; return setState({ status: "error", message: body?.message ?? body?.code ?? copy.error }); } key.current = null; setState({ status: "success", message: copy.success }); router.refresh(); } catch { setState({ status: "error", message: "Resultado incierto. Reintenta sin recargar para reutilizar la clave idempotente." }); } }
  return <div className="compact-stack">{action === "post" ? <label>Fecha contable<input type="date" value={postingDate} onChange={(event) => setPostingDate(event.currentTarget.value)} /></label> : null}<button className={action === "cancel" ? "button button-danger-soft button-small" : "button button-secondary button-small"} type="button" onClick={run} disabled={state.status === "submitting"}>{state.status === "submitting" ? copy.progress : copy.label}</button><Message state={state} /></div>;
}

function Message({ state }: { state: State }) { return state.status === "success" || state.status === "error" ? <p className={state.status === "error" ? "message error" : "message"} role={state.status === "error" ? "alert" : "status"}>{state.message}</p> : null; }
async function headers(idempotencyKey: string): Promise<Record<string, string>> { return { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey, "X-CSRF-Token": await fetchCsrfToken() }; }
async function responseBody(response: Response): Promise<{ message?: string; code?: string } | null> { return await response.json().catch(() => null) as { message?: string; code?: string } | null; }
function optional(value: FormDataEntryValue | null): string | null { const text = typeof value === "string" ? value.trim() : ""; return text || null; }
function actionCopy(action: Action) { if (action === "approve") return { label: "Aprobar", progress: "Aprobando...", confirmation: "El reembolso quedará listo para contabilizar. ¿Continuar?", success: "Reembolso aprobado.", error: "No se pudo aprobar." }; if (action === "post") return { label: "Contabilizar", progress: "Contabilizando...", confirmation: "Se registrará la entrada y el asiento. ¿Continuar?", success: "Reembolso contabilizado.", error: "No se pudo contabilizar." }; return { label: "Cancelar", progress: "Cancelando...", confirmation: "Se liberará el saldo reservado. ¿Continuar?", success: "Solicitud cancelada.", error: "No se pudo cancelar." }; }
function today(): string { return new Date().toISOString().slice(0, 10); }
function formatDate(value: string): string { return new Date(`${value}T00:00:00.000Z`).toLocaleDateString("es-ES"); }
function formatMoney(value: string): string { return `${value} EUR`; }
