import Link from "next/link";
import { listPurchases, listPurchasesSchema } from "@/modules/purchases/application/purchases";
import { PurchaseDraftCreateForm } from "@/modules/purchases/presentation/PurchaseForms";
import { listSuppliers } from "@/modules/suppliers/application/suppliers";
import { authorizePagePermission } from "@/modules/platform/presentation/pageAccess";

export const dynamic = "force-dynamic";
export default async function PurchasesPage({ searchParams }: { searchParams: Promise<{ status?: string; paymentStatus?: string; supplierId?: string; search?: string }> }) {
  const authorization = await authorizePagePermission("Purchases.View"); const params = await searchParams;
  if (!authorization.ok) return <main className="shell"><header className="topbar"><div className="brand">CriGestión</div><Link className="button button-secondary" href="/app">Volver</Link></header><section className="content"><div className="panel stack"><h1>Compras</h1><p className="message error">{authorization.message}</p></div></section></main>;
  const parsed = listPurchasesSchema.safeParse({ limit: 50, status: params.status || undefined, paymentStatus: params.paymentStatus || undefined, supplierId: params.supplierId || undefined, search: params.search || undefined });
  const [result, suppliers] = await Promise.all([parsed.success ? listPurchases(parsed.data, authorization.user) : { purchases: [] }, listSuppliers({ limit: 100, status: "ACTIVE" }, authorization.user)]);
  const canDraft = authorization.user.permissions.includes("Purchases.ManageDrafts");
  return <main className="shell"><header className="topbar"><div className="brand">CriGestión</div><div className="button-row"><Link className="button button-secondary" href="/app/treasury/supplier-payments">Pagos proveedor</Link><Link className="button button-secondary" href="/app">Inicio</Link></div></header><section className="content stack"><div className="panel stack"><div><p className="eyebrow">Compras</p><h1>Facturas de proveedor</h1><p className="muted">Borradores, registro contable, IVA soportado, stock y seguimiento de pago.</p></div><form className="filter-row" action="/app/purchases"><label>Buscar<input name="search" defaultValue={params.search ?? ""} placeholder="Número o proveedor"/></label><label>Estado<select name="status" defaultValue={params.status ?? ""}><option value="">Todos</option><option value="DRAFT">Borrador</option><option value="REGISTERED">Registrada</option><option value="VOIDED">Anulada</option></select></label><label>Pago<select name="paymentStatus" defaultValue={params.paymentStatus ?? ""}><option value="">Todos</option><option value="PENDING">Pendiente</option><option value="PARTIALLY_PAID">Parcial</option><option value="PAID">Pagada</option></select></label><label>Proveedor<select name="supplierId" defaultValue={params.supplierId ?? ""}><option value="">Todos</option>{suppliers.suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.code} - {supplier.legalName}</option>)}</select></label><button className="button">Filtrar</button></form>{!parsed.success ? <p className="message error">Filtros inválidos.</p> : null}<div className="table-wrap"><table><thead><tr><th>Factura</th><th>Proveedor</th><th>Fecha</th><th className="numeric">Total</th><th>Estados</th><th>Acciones</th></tr></thead><tbody>{result.purchases.length ? result.purchases.map((purchase) => <tr key={purchase.id}><td><strong>{purchase.supplierInvoiceNumber}</strong></td><td>{purchase.supplierName}<span className="cell-detail">{purchase.supplierCode}</span></td><td>{purchase.accountingDate}</td><td className="numeric">{purchase.total} EUR</td><td><span className="badge neutral">{statusLabel(purchase.status)}</span> <span className="badge neutral">{paymentLabel(purchase.paymentStatus)}</span></td><td><Link className="button button-secondary button-small" href={`/app/purchases/${purchase.id}`}>Abrir</Link></td></tr>) : <tr><td colSpan={6}>No hay compras para mostrar.</td></tr>}</tbody></table></div></div>{canDraft ? <div className="panel stack"><PurchaseDraftCreateForm suppliers={suppliers.suppliers.map((supplier) => ({ id: supplier.id, code: supplier.code, legalName: supplier.legalName }))}/></div> : null}</section></main>;
}
function statusLabel(value: string) { return ({ DRAFT: "Borrador", REGISTERED: "Registrada", RECTIFIED: "Rectificada", VOIDED: "Anulada" } as Record<string, string>)[value] ?? value; }
function paymentLabel(value: string) { return ({ PENDING: "Pendiente", PARTIALLY_PAID: "Pago parcial", PAID: "Pagada", NOT_APPLICABLE: "No aplica" } as Record<string, string>)[value] ?? value; }
