import Link from "next/link";
import { z } from "zod";
import { authorizePagePermission } from "@/modules/platform/presentation/pageAccess";
import { listBankAccounts } from "@/modules/treasury/application/banking";
import { getSupplierCredit, listSupplierCredits, listSupplierCreditsSchema, type SupplierCreditDetail } from "@/modules/treasury/application/supplierCredits";
import { SupplierCreditApplicationForm, SupplierCreditRefundAction, SupplierCreditRefundRequestForm } from "@/modules/treasury/presentation/SupplierCreditForms";

export const dynamic = "force-dynamic";
type Props = { searchParams: Promise<{ cursor?: string; status?: string; supplierId?: string; search?: string; creditId?: string }> };
const selectedSchema = z.string().uuid();

export default async function SupplierCreditsPage({ searchParams }: Props) {
  const authorization = await authorizePagePermission("Treasury.ViewSupplierCredits"); const params = await searchParams;
  if (!authorization.ok) return unauthorized(authorization.message);
  const query = listSupplierCreditsSchema.safeParse({ limit: 25, cursor: params.cursor, status: params.status, supplierId: params.supplierId, search: params.search });
  const list = query.success ? await listSupplierCredits(query.data, authorization.user) : emptyList();
  const selectedId = selectedSchema.safeParse(params.creditId); const selected = selectedId.success ? await getSupplierCredit(selectedId.data, authorization.user) : null;
  const permissions = authorization.user.permissions; const canRequest = permissions.includes("Treasury.RequestSupplierRefunds");
  const bankAccounts = canRequest ? (await listBankAccounts(authorization.user)).bankAccounts : [];
  return <main className="shell"><header className="topbar"><div className="brand">CriGestión</div><div className="button-row"><Link className="button button-secondary" href="/app/treasury">Tesorería</Link><Link className="button button-secondary" href="/app">Inicio</Link></div></header><section className="content stack">
    <div className="panel stack"><div><p className="eyebrow">Tesorería de proveedores</p><h1>Saldos a favor con proveedores</h1><p className="muted">Créditos nacidos de rectificativas totalmente pagadas, compensaciones y reembolsos trazables.</p></div>
      <div className="data-grid"><Metric label="Créditos" value={String(list.summary.count)} /><Metric label="Original" value={money(list.summary.originalAmount)} /><Metric label="Aplicado" value={money(list.summary.appliedAmount)} /><Metric label="Reembolsado" value={money(list.summary.refundedAmount)} /><Metric label="Disponible" value={money(list.summary.availableAmount)} /></div>
      <form className="filter-row" action="/app/treasury/supplier-credits">{params.supplierId ? <input type="hidden" name="supplierId" value={params.supplierId} /> : null}<label>Buscar<input name="search" maxLength={120} defaultValue={params.search ?? ""} placeholder="Proveedor o rectificativa" /></label><label>Estado<select name="status" defaultValue={params.status ?? "WITH_BALANCE"}><option value="WITH_BALANCE">Con saldo</option><option value="EXHAUSTED">Agotados</option><option value="ALL">Todos</option></select></label><div className="form-actions"><button className="button">Filtrar</button><Link className="button button-secondary" href="/app/treasury/supplier-credits">Limpiar</Link></div></form>
      {!query.success ? <p className="message error" role="alert">Los filtros no son válidos.</p> : null}
      <div className="table-wrap"><table><caption className="sr-only">Créditos de proveedores</caption><thead><tr><th>Origen</th><th>Proveedor</th><th>Estado</th><th>Original</th><th>Aplicado</th><th>Reembolsado</th><th>Reservado</th><th>Disponible</th><th>Acciones</th></tr></thead><tbody>{list.credits.map((credit) => <tr key={credit.id}><td><strong>{credit.sourcePurchase.supplierInvoiceNumber}</strong><span className="cell-detail">{date(credit.sourcePurchase.issueDate)}</span></td><td><strong>{credit.supplier.legalName}</strong><span className="cell-detail">{credit.supplier.code}</span></td><td>{statusLabel(credit.status)}</td><td>{money(credit.originalAmount)}</td><td>{money(credit.appliedAmount)}</td><td>{money(credit.postedRefundAmount)}</td><td>{money(credit.reservedRefundAmount)}</td><td><strong>{money(credit.availableAmount)}</strong></td><td><Link className="button button-secondary button-small" href={detailHref(credit.id, params)}>Gestionar</Link></td></tr>)}</tbody></table></div>
      {list.credits.length === 0 ? <p className="muted">No hay saldos que coincidan con los filtros.</p> : null}{list.nextCursor ? <Link className="button button-secondary" href={nextHref(list.nextCursor, params)}>Siguiente página</Link> : null}
    </div>
    {params.creditId && !selectedId.success ? <div className="panel"><p className="message error">El identificador no es válido.</p></div> : null}{selectedId.success && !selected ? <div className="panel"><p className="message error">El crédito no existe.</p></div> : null}
    {selected ? <Detail credit={selected} currentUserId={authorization.user.id} canApply={permissions.includes("Treasury.ApplySupplierCredits")} canRequest={canRequest} canApprove={permissions.includes("Treasury.ApproveSupplierRefunds")} canPost={permissions.includes("Treasury.PostSupplierRefunds")} canViewAccounting={permissions.includes("Accounting.View")} bankAccounts={bankAccounts} /> : null}
  </section></main>;
}

function Detail({ credit, currentUserId, canApply, canRequest, canApprove, canPost, canViewAccounting, bankAccounts }: { credit: SupplierCreditDetail; currentUserId: string; canApply: boolean; canRequest: boolean; canApprove: boolean; canPost: boolean; canViewAccounting: boolean; bankAccounts: Awaited<ReturnType<typeof listBankAccounts>>["bankAccounts"] }) {
  const available = Number(credit.availableAmount) > 0;
  return <><div className="panel stack" id="credit-detail"><div className="split-header"><div><p className="eyebrow">Detalle del saldo</p><h2>{credit.supplier.legalName}</h2><p className="muted">Origen <Link href={`/app/purchases/${credit.sourcePurchase.id}`}>{credit.sourcePurchase.supplierInvoiceNumber}</Link> · {credit.supplier.code}</p></div><span className="status">{statusLabel(credit.status)}</span></div>
    <div className="data-grid"><Metric label="Original" value={money(credit.originalAmount)} /><Metric label="Aplicado" value={money(credit.appliedAmount)} /><Metric label="Reembolsado" value={money(credit.postedRefundAmount)} /><Metric label="Reservado" value={money(credit.reservedRefundAmount)} /><Metric label="Disponible" value={money(credit.availableAmount)} /></div>
    <h3>Compensaciones</h3><div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Compra</th><th>Importe</th></tr></thead><tbody>{credit.applications.length === 0 ? <tr><td colSpan={3}>No hay compensaciones.</td></tr> : credit.applications.map((row) => <tr key={row.id}><td>{date(row.applicationDate)}</td><td><Link href={`/app/purchases/${row.targetPurchase.id}`}>{row.targetPurchase.supplierInvoiceNumber}</Link></td><td>{money(row.amount)}</td></tr>)}</tbody></table></div>
    <h3>Reembolsos</h3><div className="table-wrap"><table><thead><tr><th>Solicitud</th><th>Importe</th><th>Método</th><th>Motivo</th><th>Estado</th><th>Asiento</th><th>Acciones</th></tr></thead><tbody>{credit.refunds.length === 0 ? <tr><td colSpan={7}>No hay solicitudes.</td></tr> : credit.refunds.map((refund) => <tr key={refund.id}><td>{date(refund.requestedDate)}{refund.postingDate ? <span className="cell-detail">Contable {date(refund.postingDate)}</span> : null}</td><td>{money(refund.amount)}</td><td>{refund.paymentMethod === "CASH" ? "Caja" : <>Transferencia<span className="cell-detail">{refund.bankAccount?.name} · {refund.bankAccount?.maskedIban}</span></>}</td><td>{reasonLabel(refund.reasonCode)}</td><td>{refundLabel(refund.status)}</td><td>{refund.accountingEntry ? canViewAccounting ? <Link href={`/app/accounting?entryId=${refund.accountingEntry.id}`}>{refund.accountingEntry.number}</Link> : "Creado" : "—"}</td><td><div className="button-row">{refund.status === "REQUESTED" && canApprove && refund.requestedById !== currentUserId ? <SupplierCreditRefundAction refundId={refund.id} action="approve" /> : null}{refund.status === "REQUESTED" && canRequest && refund.requestedById === currentUserId ? <SupplierCreditRefundAction refundId={refund.id} action="cancel" /> : null}{refund.status === "APPROVED" && canPost ? <SupplierCreditRefundAction refundId={refund.id} action="post" /> : null}</div>{refund.status === "REQUESTED" && canApprove && refund.requestedById === currentUserId ? <small>No puedes aprobar tu propia solicitud.</small> : null}</td></tr>)}</tbody></table></div>
  </div>{!available ? <div className="panel"><p className="message">El saldo está agotado; su historial permanece disponible.</p></div> : null}{available && canApply ? <div className="panel stack"><SupplierCreditApplicationForm credit={credit} /></div> : null}{available && canRequest ? <div className="panel stack"><SupplierCreditRefundRequestForm credit={credit} bankAccounts={bankAccounts} /></div> : null}</>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div><span className="data-label">{label}</span><strong>{value}</strong></div>; }
function unauthorized(message: string) { return <main className="shell"><section className="content"><div className="panel"><h1>Saldos de proveedores</h1><p className="message error">{message}</p></div></section></main>; }
function emptyList() { return { credits: [], summary: { count: 0, originalAmount: "0.00", appliedAmount: "0.00", refundedAmount: "0.00", availableAmount: "0.00" }, nextCursor: null }; }
function statusLabel(value: SupplierCreditDetail["status"]) { return value === "AVAILABLE" ? "Disponible" : value === "PARTIALLY_USED" ? "Parcial" : "Agotado"; }
function refundLabel(value: SupplierCreditDetail["refunds"][number]["status"]) { return value === "REQUESTED" ? "Solicitado" : value === "APPROVED" ? "Aprobado" : value === "POSTED" ? "Contabilizado" : "Cancelado"; }
function reasonLabel(value: string) { return value === "SUPPLIER_REQUEST" ? "Solicitud del proveedor" : value === "DUPLICATE_OR_EXCESS" ? "Duplicidad o exceso" : value === "OPERATION_CANCELLED" ? "Operación cancelada" : "Otro"; }
function date(value: string) { return new Date(`${value}T00:00:00.000Z`).toLocaleDateString("es-ES"); }
function money(value: string) { return `${value} EUR`; }
function detailHref(id: string, params: { status?: string; supplierId?: string; search?: string }) { const query = new URLSearchParams({ creditId: id }); if (params.status) query.set("status", params.status); if (params.supplierId) query.set("supplierId", params.supplierId); if (params.search) query.set("search", params.search); return `/app/treasury/supplier-credits?${query.toString()}#credit-detail`; }
function nextHref(cursor: string, params: { status?: string; supplierId?: string; search?: string }) { const query = new URLSearchParams({ cursor }); if (params.status) query.set("status", params.status); if (params.supplierId) query.set("supplierId", params.supplierId); if (params.search) query.set("search", params.search); return `/app/treasury/supplier-credits?${query.toString()}`; }
