import Link from "next/link";
import { authorizePagePermission } from "@/modules/platform/presentation/pageAccess";
import { listBankAccounts, listBankMovements, listBankMovementsSchema, listReconciliationCandidates, listReconciliationProposals } from "@/modules/treasury/application/banking";
import { BankAccountCreateForm, BankMovementCreateForm, BankReconciliationForm, UndoBankReconciliationButton } from "@/modules/treasury/presentation/BankingForms";

export const dynamic = "force-dynamic";

export default async function BankingPage({ searchParams }: { searchParams: Promise<{ status?: string; movementId?: string; search?: string }> }) {
  const authorization = await authorizePagePermission("Treasury.ViewBanking");
  if (!authorization.ok) return <main className="shell"><section className="content"><div className="panel stack"><h1>Conciliacion bancaria</h1><p className="message error">{authorization.message}</p></div></section></main>;
  const params = await searchParams;
  const query = listBankMovementsSchema.safeParse({ limit: 50, status: params.status, search: params.search });
  const [accounts, movements] = await Promise.all([listBankAccounts(authorization.user), listBankMovements(query.success ? query.data : { limit: 50, status: "ALL" }, authorization.user)]);
  const selected = params.movementId ? movements.bankMovements.find((movement) => movement.id === params.movementId) : undefined;
  const [proposalResult, manualResult] = selected ? await Promise.all([listReconciliationProposals({ movementId: selected.id, limit: 25 }, authorization.user), listReconciliationCandidates({ movementId: selected.id, limit: 50 }, authorization.user)]) : [null, null];
  const proposedIds = new Set(proposalResult?.proposals.map((proposal) => proposal.paymentId) ?? []);
  const candidateResult = proposalResult && manualResult ? { candidates: [...proposalResult.proposals, ...manualResult.candidates.filter((candidate) => !proposedIds.has(candidate.paymentId))] } : null;
  const canReconcile = authorization.user.permissions.includes("Treasury.ReconcileBanking");
  return <main className="shell"><header className="topbar"><div className="brand">CriGestión</div><div className="button-row"><Link className="button button-secondary" href="/app/treasury">Tesoreria</Link><Link className="button button-secondary" href="/app">Inicio</Link></div></header><section className="content stack"><div className="panel stack"><div><p className="eyebrow">Tesoreria</p><h1>Conciliacion bancaria</h1><p className="muted">Movimientos manuales y conciliacion verificable contra cobros ya registrados.</p></div>{canReconcile ? <><BankAccountCreateForm /><BankMovementCreateForm accounts={accounts.bankAccounts} /></> : null}</div><div className="panel stack"><form className="filter-grid" method="get"><label>Estado<select name="status" defaultValue={params.status ?? "ALL"}><option value="ALL">Todos</option><option value="PENDING">Pendientes</option><option value="PARTIALLY_RECONCILED">Parciales</option><option value="RECONCILED">Conciliados</option></select></label><label>Buscar<input name="search" defaultValue={params.search ?? ""} /></label><button className="button" type="submit">Filtrar</button></form><div className="table-scroll"><table><thead><tr><th>Fecha</th><th>Cuenta</th><th>Referencia</th><th className="numeric">Importe</th><th className="numeric">Conciliado</th><th className="numeric">Pendiente</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{movements.bankMovements.map((movement) => <tr key={movement.id}><td>{movement.bookingDate}</td><td>{movement.bankAccount.name}<small>{movement.bankAccount.maskedIban}</small></td><td>{movement.reference ?? "—"}</td><td className="numeric">{movement.amount} EUR</td><td className="numeric">{movement.reconciledAmount} EUR</td><td className="numeric">{movement.pendingAmount} EUR</td><td>{statusLabel(movement.status)}</td><td><div className="button-row">{canReconcile && Number(movement.amount) > 0 && movement.pendingAmount !== "0.00" ? <Link className="button button-secondary button-small" href={`/app/treasury/banking?movementId=${movement.id}`}>Conciliar</Link> : null}{canReconcile ? movement.activeReconciliations.map((item) => <UndoBankReconciliationButton key={item.id} reconciliationId={item.id} />) : null}</div></td></tr>)}</tbody></table></div>{movements.bankMovements.length === 0 ? <p className="muted">No hay movimientos para los filtros seleccionados.</p> : null}</div>{selected && candidateResult && canReconcile ? <div className="panel stack"><BankReconciliationForm movement={selected} candidates={candidateResult.candidates} /></div> : null}</section></main>;
}

function statusLabel(status: string): string { return status === "PENDING" ? "Pendiente" : status === "PARTIALLY_RECONCILED" ? "Parcial" : "Conciliado"; }
