import Link from "next/link";
import { authorizePagePermission } from "@/modules/platform/presentation/pageAccess";
import { listSupportIncidentFilterReferences, listSupportIncidents, listSupportIncidentsSchema, listSupportReferences } from "@/modules/support/application/incidents";
import { SupportIncidentCreateForm } from "@/modules/support/presentation/SupportIncidentCreateForm";
import { getSupportDashboard } from "@/modules/support/application/dashboard";

export const dynamic = "force-dynamic";
type IncidentParams = { cursor?: string; status?: string; priority?: string; responsibleUserId?: string; customerId?: string; categoryId?: string; activeCollaboratorUserId?: string; createdFrom?: string; createdTo?: string; search?: string };
type Props = { searchParams: Promise<IncidentParams> };

export default async function SupportPage({ searchParams }: Props) {
  const authorization = await authorizePagePermission("Support.View");
  if (!authorization.ok) return <Denied message={authorization.message}/>;
  const params = await searchParams;
  const parsed = listSupportIncidentsSchema.safeParse({ limit: 25, ...params });
  const safeParams: IncidentParams = parsed.success ? parsed.data : {};
  const result = parsed.success ? await listSupportIncidents(parsed.data, authorization.user) : { incidents: [], nextCursor: null, rateLimited: false };
  const canCreate = authorization.user.permissions.includes("Support.Create");
  const dashboardResult = await getSupportDashboard(authorization.user);
  const dashboard = dashboardResult.ok ? dashboardResult.value : null;
  const filterReferences = await listSupportIncidentFilterReferences(safeParams.customerId);
  const references = canCreate ? await listSupportReferences(safeParams.customerId) : null;
  return <main className="shell"><header className="topbar"><div className="brand">CriGestión</div><Link className="button button-secondary" href="/app">Volver</Link></header><section className="content stack">
    <div className="panel stack"><div><p className="eyebrow">Atención al cliente</p><h1>Panel de soporte</h1><p className="muted">Carga operativa, avisos y seguimiento interno sin exponer datos económicos.</p><div className="form-actions"><Link className="button button-secondary" href="/app/notifications">Notificaciones ({dashboard?.unreadNotifications.count ?? 0})</Link>{authorization.user.permissions.includes("Support.ViewIndicators") ? <Link className="button button-secondary" href="/app/support/indicators">Indicadores</Link> : null}{authorization.user.permissions.includes("Support.ViewCommunications") ? <Link className="button button-secondary" href="/app/support/communications">Comunicaciones</Link> : null}{authorization.user.permissions.includes("Support.ManageCategories") ? <Link className="button button-secondary" href="/app/support/categories">Categorías</Link> : null}</div></div>
      {dashboard ? <SupportDashboard dashboard={dashboard} actorId={authorization.user.id}/> : <p className="message error">No se pudo cargar la foto operativa.</p>}
      <div><h2>Incidencias</h2><p className="muted">Consulta y filtra el registro completo.</p></div>
      <form className="filter-row" action="/app/support"><label>Buscar<input name="search" minLength={3} maxLength={120} defaultValue={safeParams.search ?? ""} placeholder="Número, título o descripción"/></label><label>Cliente<select name="customerId" defaultValue={safeParams.customerId ?? ""}><option value="">Todos</option>{filterReferences.customers.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.legalName}</option>)}</select></label><label>Responsable<select name="responsibleUserId" defaultValue={safeParams.responsibleUserId ?? ""}><option value="">Todos</option>{filterReferences.responsibleUsers.map((item) => <option key={item.id} value={item.id}>{item.displayName}{item.status === "ACTIVE" ? "" : " · Inactivo"}</option>)}</select></label><label>Colaborador activo<select name="activeCollaboratorUserId" defaultValue={safeParams.activeCollaboratorUserId ?? ""}><option value="">Todos</option>{filterReferences.collaboratorUsers.map((item) => <option key={item.id} value={item.id}>{item.displayName}{item.status === "ACTIVE" ? "" : " · Inactivo"}</option>)}</select></label><label>Categoría<select name="categoryId" defaultValue={safeParams.categoryId ?? ""}><option value="">Todas</option>{filterReferences.categories.map((item) => <option key={item.id} value={item.id}>{item.name}{item.isActive ? "" : " · Inactiva"}</option>)}</select></label><label>Estado<select name="status" defaultValue={safeParams.status ?? ""}><option value="">Todos</option><option value="NEW">Nueva</option><option value="IN_PROGRESS">En curso</option><option value="PENDING_CUSTOMER">Pendiente del cliente</option><option value="PENDING_THIRD_PARTY">Pendiente de tercero</option><option value="RESOLVED">Resuelta</option><option value="CLOSED">Cerrada</option></select></label><label>Prioridad<select name="priority" defaultValue={safeParams.priority ?? ""}><option value="">Todas</option><option value="LOW">Baja</option><option value="MEDIUM">Media</option><option value="HIGH">Alta</option><option value="URGENT">Urgente</option></select></label><label>Creada desde<input type="date" name="createdFrom" defaultValue={safeParams.createdFrom ?? ""}/></label><label>Creada hasta<input type="date" name="createdTo" defaultValue={safeParams.createdTo ?? ""}/></label><div className="form-actions"><button className="button">Filtrar</button><Link className="button button-secondary" href="/app/support">Limpiar</Link></div></form>
      {!parsed.success ? <p className="message error">Los filtros no son válidos.</p> : null}
      {result.rateLimited ? <p className="message error">Se ha superado el límite temporal de búsquedas. Inténtalo de nuevo más tarde.</p> : null}
      <div className="table-wrap"><table aria-label="Listado de incidencias"><thead><tr><th scope="col">Incidencia</th><th scope="col">Cliente</th><th scope="col">Categoría</th><th scope="col">Responsable</th><th scope="col">Prioridad</th><th scope="col">Estado</th></tr></thead><tbody>{result.incidents.length === 0 ? <tr><td colSpan={6}>No hay incidencias para mostrar.</td></tr> : result.incidents.map((incident) => <tr key={incident.id}><td><Link href={`/app/support/incidents/${incident.id}`}><strong>{incident.number}</strong></Link><span className="cell-detail">{incident.title}</span></td><td>{incident.customer.legalName}<span className="cell-detail">{incident.customer.code}{incident.customer.status === "INACTIVE" ? " · Inactivo" : ""}</span></td><td>{incident.category.name}</td><td>{incident.responsible.displayName}</td><td><span className={`badge ${incident.priority === "URGENT" ? "error" : incident.priority === "HIGH" ? "warning" : "neutral"}`}>{priorityLabel(incident.priority)}</span></td><td>{statusLabel(incident.status)}</td></tr>)}</tbody></table></div>
      {result.nextCursor ? <Link className="button button-secondary" href={nextHref(result.nextCursor, safeParams)}>Siguiente página</Link> : null}
    </div>
    {canCreate && references ? <div className="panel stack" id="new-incident"><SupportIncidentCreateForm references={references} defaultCustomerId={safeParams.customerId}/></div> : null}
  </section></main>;
}

function Denied({ message }: { message: string }) { return <main className="shell"><section className="content"><div className="panel stack"><h1>Atención al cliente</h1><p className="message error">{message}</p></div></section></main>; }
function priorityLabel(value: string) { return ({ LOW: "Baja", MEDIUM: "Media", HIGH: "Alta", URGENT: "Urgente" } as Record<string, string>)[value] ?? value; }
function statusLabel(value: string) { return ({ NEW: "Nueva", IN_PROGRESS: "En curso", PENDING_CUSTOMER: "Pendiente del cliente", PENDING_THIRD_PARTY: "Pendiente de tercero", RESOLVED: "Resuelta", CLOSED: "Cerrada" } as Record<string, string>)[value] ?? value; }
function nextHref(cursor: string, params: IncidentParams) { const query = new URLSearchParams({ cursor }); for (const key of ["status", "priority", "responsibleUserId", "customerId", "categoryId", "activeCollaboratorUserId", "createdFrom", "createdTo", "search"] as const) if (params[key]) query.set(key, params[key]!); return `/app/support?${query}`; }

type Dashboard = import("@/modules/support/application/dashboard").SupportDashboardDto;
function SupportDashboard({ dashboard, actorId }: { dashboard: Dashboard; actorId: string }) { return <div className="stack">
  <section className="stack" aria-labelledby="support-summary"><div><h2 id="support-summary">Resumen operativo</h2><p className="muted">Incidencias canónicas abiertas a <time dateTime={dashboard.asOf}>{formatMadrid(dashboard.asOf)}</time>.</p></div><div className="summary-grid">
    <SummaryLink href="/app/support?status=NEW" label="Nuevas" count={dashboard.snapshot.newCount}/><SummaryLink href="/app/support?status=IN_PROGRESS" label="En curso" count={dashboard.snapshot.inProgressCount}/><SummaryLink href="/app/support?status=PENDING_CUSTOMER" label="Pendiente cliente" count={dashboard.snapshot.pendingCustomerCount}/><SummaryLink href="/app/support?status=PENDING_THIRD_PARTY" label="Pendiente tercero" count={dashboard.snapshot.pendingThirdPartyCount}/><SummaryLink href="/app/support?priority=URGENT" label="Urgentes" count={dashboard.snapshot.urgentCount}/><SummaryLink href={`/app/support?responsibleUserId=${actorId}`} label="Mis incidencias" count={dashboard.snapshot.mineCount}/>
  </div></section>
  <section className="stack" aria-labelledby="my-support-incidents"><h2 id="my-support-incidents">Mis incidencias</h2><div className="table-wrap"><table aria-label="Mis incidencias abiertas"><thead><tr><th scope="col">Incidencia</th><th scope="col">Prioridad</th><th scope="col">Estado</th></tr></thead><tbody>{dashboard.myIncidents.length ? dashboard.myIncidents.map((incident) => <tr key={incident.id}><td><Link href={`/app/support/incidents/${incident.id}`}><strong>{incident.number}</strong></Link><span className="cell-detail">{incident.title}</span></td><td>{priorityLabel(incident.priority)}</td><td>{statusLabel(incident.status)}</td></tr>) : <tr><td colSpan={3}>No tienes incidencias abiertas asignadas.</td></tr>}</tbody></table></div></section>
  {dashboard.assignedByTechnician ? <section className="stack" aria-labelledby="support-load"><h2 id="support-load">Carga por técnico</h2><div className="table-wrap"><table aria-label="Incidencias abiertas asignadas por técnico"><thead><tr><th scope="col">Técnico</th><th scope="col">Abiertas</th></tr></thead><tbody>{dashboard.assignedByTechnician.length ? dashboard.assignedByTechnician.map((technician) => <tr key={technician.id}><td>{technician.displayName}</td><td>{technician.count}</td></tr>) : <tr><td colSpan={2}>No hay incidencias abiertas asignadas.</td></tr>}</tbody></table></div></section> : null}
  {dashboard.latestCommunications ? <section className="stack" aria-labelledby="latest-communications"><div><h2 id="latest-communications">Últimas comunicaciones</h2><Link href="/app/support/communications">Ver todas</Link></div><div className="table-wrap"><table aria-label="Últimas comunicaciones"><thead><tr><th scope="col">Fecha</th><th scope="col">Canal</th><th scope="col">Cliente</th><th scope="col">Incidencia</th></tr></thead><tbody>{dashboard.latestCommunications.length ? dashboard.latestCommunications.map((communication) => <tr key={communication.id}><td><Link href={`/app/support/communications/${communication.id}`}>{formatMadrid(communication.occurredAt)}</Link></td><td>{communication.channel === "PHONE" ? "Teléfono" : "WhatsApp"} · {communication.direction === "INBOUND" ? "Entrante" : "Saliente"}</td><td>{communication.customer.legalName}<span className="cell-detail">{communication.customer.code}</span></td><td>{communication.incident ? <Link href={`/app/support/incidents/${communication.incident.id}`}>{communication.incident.number}</Link> : "Sin incidencia"}</td></tr>) : <tr><td colSpan={4}>No hay comunicaciones registradas.</td></tr>}</tbody></table></div></section> : null}
  <section className="stack" aria-labelledby="pending-notifications"><div><h2 id="pending-notifications">Notificaciones pendientes</h2><Link href="/app/notifications">Ver bandeja ({dashboard.unreadNotifications.count})</Link></div><div className="table-wrap"><table aria-label="Notificaciones pendientes"><thead><tr><th scope="col">Incidencia</th><th scope="col">Tipo</th><th scope="col">Fecha</th></tr></thead><tbody>{dashboard.unreadNotifications.items.length ? dashboard.unreadNotifications.items.map((notification) => <tr key={notification.id}><td><Link href={notification.incident.href}>{notification.incident.number}</Link></td><td>{notificationLabel(notification.messageCode)}</td><td>{formatMadrid(notification.createdAt)}</td></tr>) : <tr><td colSpan={3}>No tienes notificaciones pendientes.</td></tr>}</tbody></table></div></section>
</div>; }
function SummaryLink({ href, label, count }: { href: string; label: string; count: number }) { return <Link className="summary-card" href={href} aria-label={`${count} ${label.toLocaleLowerCase("es-ES")}`}><strong>{count}</strong><span>{label}</span></Link>; }
function formatMadrid(value: string) { return new Intl.DateTimeFormat("es-ES", { dateStyle: "short", timeStyle: "short", timeZone: "Europe/Madrid" }).format(new Date(value)); }
function notificationLabel(code: string) { return ({ "support.incident.assigned": "Nueva asignación", "support.incident.urgent": "Incidencia urgente", "support.incident.reassigned": "Reasignación", "support.incident.collaborator-added": "Colaboración", "support.incident.collaborator-action": "Nueva actuación", "support.incident.reopened": "Reapertura", "support.incident.merged": "Fusión" } as Record<string, string>)[code] ?? "Actualización de incidencia"; }
