ALTER TYPE "PurchaseInvoiceStatus" ADD VALUE IF NOT EXISTS 'RECTIFIED';
ALTER TYPE "AccountingEntryOrigin" ADD VALUE IF NOT EXISTS 'PURCHASE_RECTIFICATION';
ALTER TYPE "CatalogStockMovementType" ADD VALUE IF NOT EXISTS 'PURCHASE_RETURN';
