ALTER TYPE "AccountingEntryOrigin" ADD VALUE IF NOT EXISTS 'REGULARIZATION';
ALTER TYPE "AccountingEntryOrigin" ADD VALUE IF NOT EXISTS 'CLOSING';
ALTER TYPE "AccountingEntryOrigin" ADD VALUE IF NOT EXISTS 'OPENING';
