ALTER TYPE "InvoicePaymentStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE "InvoiceDueDateStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE "AccountingEntryOrigin" ADD VALUE IF NOT EXISTS 'INVOICE_VOIDING';
